/*
Felorx API

Testing OpsCryptoAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package felorx

import (
	"context"
	openapiclient "github.com/felorx/felorx-api-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_felorx_OpsCryptoAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test OpsCryptoAPIService GetVault", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.OpsCryptoAPI.GetVault(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OpsCryptoAPIService PutVault", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.OpsCryptoAPI.PutVault(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
