/*
Felorx API

Testing OpenAiCompatibleChatAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package felorx

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/felorx/felorx-api-go"
)

func Test_felorx_OpenAiCompatibleChatAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test OpenAiCompatibleChatAPIService CreatePostApiAiV1ChatCompletions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.OpenAiCompatibleChatAPI.CreatePostApiAiV1ChatCompletions(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
