/*
Felorx API

Testing AuthCenterAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package felorx

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/felorx/felorx-api-go"
)

func Test_felorx_AuthCenterAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AuthCenterAPIService GetAuthorizedApps", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AuthCenterAPI.GetAuthorizedApps(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AuthCenterAPIService GetSummaryGetApiAppAuthCenterSummary", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AuthCenterAPI.GetSummaryGetApiAppAuthCenterSummary(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AuthCenterAPIService RevokeAuthorizedApp", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var clientId string

		httpRes, err := apiClient.AuthCenterAPI.RevokeAuthorizedApp(context.Background(), clientId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
