/*
Felorx API

Testing BuildRecordAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package felorx

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/felorx/felorx-api-go"
)

func Test_felorx_BuildRecordAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BuildRecordAPIService CreateBuildRecord", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BuildRecordAPI.CreateBuildRecord(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BuildRecordAPIService DeleteBuildRecordById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.BuildRecordAPI.DeleteBuildRecordById(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BuildRecordAPIService GetBuildRecordById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.BuildRecordAPI.GetBuildRecordById(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BuildRecordAPIService GetBuildRecordList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BuildRecordAPI.GetBuildRecordList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BuildRecordAPIService GetByCiBuildId", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ciBuildId string

		resp, httpRes, err := apiClient.BuildRecordAPI.GetByCiBuildId(context.Background(), ciBuildId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BuildRecordAPIService GetLatestGetApiAppBuildRecordLatestAppId", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var appId string

		resp, httpRes, err := apiClient.BuildRecordAPI.GetLatestGetApiAppBuildRecordLatestAppId(context.Background(), appId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BuildRecordAPIService MarkAsBuilding", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.BuildRecordAPI.MarkAsBuilding(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BuildRecordAPIService MarkAsCanceledPostApiAppBuildRecordIdMarkAsCanceled", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.BuildRecordAPI.MarkAsCanceledPostApiAppBuildRecordIdMarkAsCanceled(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BuildRecordAPIService MarkAsFailedPostApiAppBuildRecordIdMarkAsFailed", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.BuildRecordAPI.MarkAsFailedPostApiAppBuildRecordIdMarkAsFailed(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BuildRecordAPIService MarkAsSucceededPostApiAppBuildRecordIdMarkAsSucceeded", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.BuildRecordAPI.MarkAsSucceededPostApiAppBuildRecordIdMarkAsSucceeded(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BuildRecordAPIService UpdateBuildRecord", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.BuildRecordAPI.UpdateBuildRecord(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
