/*
Felorx API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package felorx

import (
	"encoding/json"
)

// checks if the CreditAccountDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreditAccountDto{}

// CreditAccountDto struct for CreditAccountDto
type CreditAccountDto struct {
	AppId        *string                `json:"appId,omitempty"`
	Balance      *int32                 `json:"balance,omitempty"`
	RecentLedger []CreditLedgerEntryDto `json:"recentLedger,omitempty"`
}

// NewCreditAccountDto instantiates a new CreditAccountDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreditAccountDto() *CreditAccountDto {
	this := CreditAccountDto{}
	return &this
}

// NewCreditAccountDtoWithDefaults instantiates a new CreditAccountDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreditAccountDtoWithDefaults() *CreditAccountDto {
	this := CreditAccountDto{}
	return &this
}

// GetAppId returns the AppId field value if set, zero value otherwise.
func (o *CreditAccountDto) GetAppId() string {
	if o == nil || IsNil(o.AppId) {
		var ret string
		return ret
	}
	return *o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditAccountDto) GetAppIdOk() (*string, bool) {
	if o == nil || IsNil(o.AppId) {
		return nil, false
	}
	return o.AppId, true
}

// HasAppId returns a boolean if a field has been set.
func (o *CreditAccountDto) HasAppId() bool {
	if o != nil && !IsNil(o.AppId) {
		return true
	}

	return false
}

// SetAppId gets a reference to the given string and assigns it to the AppId field.
func (o *CreditAccountDto) SetAppId(v string) {
	o.AppId = &v
}

// GetBalance returns the Balance field value if set, zero value otherwise.
func (o *CreditAccountDto) GetBalance() int32 {
	if o == nil || IsNil(o.Balance) {
		var ret int32
		return ret
	}
	return *o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditAccountDto) GetBalanceOk() (*int32, bool) {
	if o == nil || IsNil(o.Balance) {
		return nil, false
	}
	return o.Balance, true
}

// HasBalance returns a boolean if a field has been set.
func (o *CreditAccountDto) HasBalance() bool {
	if o != nil && !IsNil(o.Balance) {
		return true
	}

	return false
}

// SetBalance gets a reference to the given int32 and assigns it to the Balance field.
func (o *CreditAccountDto) SetBalance(v int32) {
	o.Balance = &v
}

// GetRecentLedger returns the RecentLedger field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreditAccountDto) GetRecentLedger() []CreditLedgerEntryDto {
	if o == nil {
		var ret []CreditLedgerEntryDto
		return ret
	}
	return o.RecentLedger
}

// GetRecentLedgerOk returns a tuple with the RecentLedger field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreditAccountDto) GetRecentLedgerOk() ([]CreditLedgerEntryDto, bool) {
	if o == nil || IsNil(o.RecentLedger) {
		return nil, false
	}
	return o.RecentLedger, true
}

// HasRecentLedger returns a boolean if a field has been set.
func (o *CreditAccountDto) HasRecentLedger() bool {
	if o != nil && !IsNil(o.RecentLedger) {
		return true
	}

	return false
}

// SetRecentLedger gets a reference to the given []CreditLedgerEntryDto and assigns it to the RecentLedger field.
func (o *CreditAccountDto) SetRecentLedger(v []CreditLedgerEntryDto) {
	o.RecentLedger = v
}

func (o CreditAccountDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreditAccountDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AppId) {
		toSerialize["appId"] = o.AppId
	}
	if !IsNil(o.Balance) {
		toSerialize["balance"] = o.Balance
	}
	if o.RecentLedger != nil {
		toSerialize["recentLedger"] = o.RecentLedger
	}
	return toSerialize, nil
}

type NullableCreditAccountDto struct {
	value *CreditAccountDto
	isSet bool
}

func (v NullableCreditAccountDto) Get() *CreditAccountDto {
	return v.value
}

func (v *NullableCreditAccountDto) Set(val *CreditAccountDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreditAccountDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreditAccountDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreditAccountDto(val *CreditAccountDto) *NullableCreditAccountDto {
	return &NullableCreditAccountDto{value: val, isSet: true}
}

func (v NullableCreditAccountDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreditAccountDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
