/*
Felorx API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package felorx

import (
	"encoding/json"
	"time"
)

// checks if the AppLocaleDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppLocaleDto{}

// AppLocaleDto struct for AppLocaleDto
type AppLocaleDto struct {
	Id *string `json:"id,omitempty"`
	CreationTime *time.Time `json:"creationTime,omitempty"`
	CreatorId NullableString `json:"creatorId,omitempty"`
	LastModificationTime NullableTime `json:"lastModificationTime,omitempty"`
	LastModifierId NullableString `json:"lastModifierId,omitempty"`
	IsDeleted *bool `json:"isDeleted,omitempty"`
	DeleterId NullableString `json:"deleterId,omitempty"`
	DeletionTime NullableTime `json:"deletionTime,omitempty"`
	AppId *string `json:"appId,omitempty"`
	LangCode NullableString `json:"langCode,omitempty"`
	CountryCode NullableString `json:"countryCode,omitempty"`
	Title NullableString `json:"title,omitempty"`
	Subtitle NullableString `json:"subtitle,omitempty"`
	ShortDesc NullableString `json:"shortDesc,omitempty"`
	FullDesc NullableString `json:"fullDesc,omitempty"`
	Keywords NullableString `json:"keywords,omitempty"`
	PromoText NullableString `json:"promoText,omitempty"`
	SupportUrl NullableString `json:"supportUrl,omitempty"`
	PrivacyUrl NullableString `json:"privacyUrl,omitempty"`
	ReleaseNote NullableString `json:"releaseNote,omitempty"`
}

// NewAppLocaleDto instantiates a new AppLocaleDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppLocaleDto() *AppLocaleDto {
	this := AppLocaleDto{}
	return &this
}

// NewAppLocaleDtoWithDefaults instantiates a new AppLocaleDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppLocaleDtoWithDefaults() *AppLocaleDto {
	this := AppLocaleDto{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AppLocaleDto) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppLocaleDto) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AppLocaleDto) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AppLocaleDto) SetId(v string) {
	o.Id = &v
}

// GetCreationTime returns the CreationTime field value if set, zero value otherwise.
func (o *AppLocaleDto) GetCreationTime() time.Time {
	if o == nil || IsNil(o.CreationTime) {
		var ret time.Time
		return ret
	}
	return *o.CreationTime
}

// GetCreationTimeOk returns a tuple with the CreationTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppLocaleDto) GetCreationTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreationTime) {
		return nil, false
	}
	return o.CreationTime, true
}

// HasCreationTime returns a boolean if a field has been set.
func (o *AppLocaleDto) HasCreationTime() bool {
	if o != nil && !IsNil(o.CreationTime) {
		return true
	}

	return false
}

// SetCreationTime gets a reference to the given time.Time and assigns it to the CreationTime field.
func (o *AppLocaleDto) SetCreationTime(v time.Time) {
	o.CreationTime = &v
}

// GetCreatorId returns the CreatorId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppLocaleDto) GetCreatorId() string {
	if o == nil || IsNil(o.CreatorId.Get()) {
		var ret string
		return ret
	}
	return *o.CreatorId.Get()
}

// GetCreatorIdOk returns a tuple with the CreatorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppLocaleDto) GetCreatorIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatorId.Get(), o.CreatorId.IsSet()
}

// HasCreatorId returns a boolean if a field has been set.
func (o *AppLocaleDto) HasCreatorId() bool {
	if o != nil && o.CreatorId.IsSet() {
		return true
	}

	return false
}

// SetCreatorId gets a reference to the given NullableString and assigns it to the CreatorId field.
func (o *AppLocaleDto) SetCreatorId(v string) {
	o.CreatorId.Set(&v)
}
// SetCreatorIdNil sets the value for CreatorId to be an explicit nil
func (o *AppLocaleDto) SetCreatorIdNil() {
	o.CreatorId.Set(nil)
}

// UnsetCreatorId ensures that no value is present for CreatorId, not even an explicit nil
func (o *AppLocaleDto) UnsetCreatorId() {
	o.CreatorId.Unset()
}

// GetLastModificationTime returns the LastModificationTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppLocaleDto) GetLastModificationTime() time.Time {
	if o == nil || IsNil(o.LastModificationTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastModificationTime.Get()
}

// GetLastModificationTimeOk returns a tuple with the LastModificationTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppLocaleDto) GetLastModificationTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastModificationTime.Get(), o.LastModificationTime.IsSet()
}

// HasLastModificationTime returns a boolean if a field has been set.
func (o *AppLocaleDto) HasLastModificationTime() bool {
	if o != nil && o.LastModificationTime.IsSet() {
		return true
	}

	return false
}

// SetLastModificationTime gets a reference to the given NullableTime and assigns it to the LastModificationTime field.
func (o *AppLocaleDto) SetLastModificationTime(v time.Time) {
	o.LastModificationTime.Set(&v)
}
// SetLastModificationTimeNil sets the value for LastModificationTime to be an explicit nil
func (o *AppLocaleDto) SetLastModificationTimeNil() {
	o.LastModificationTime.Set(nil)
}

// UnsetLastModificationTime ensures that no value is present for LastModificationTime, not even an explicit nil
func (o *AppLocaleDto) UnsetLastModificationTime() {
	o.LastModificationTime.Unset()
}

// GetLastModifierId returns the LastModifierId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppLocaleDto) GetLastModifierId() string {
	if o == nil || IsNil(o.LastModifierId.Get()) {
		var ret string
		return ret
	}
	return *o.LastModifierId.Get()
}

// GetLastModifierIdOk returns a tuple with the LastModifierId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppLocaleDto) GetLastModifierIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastModifierId.Get(), o.LastModifierId.IsSet()
}

// HasLastModifierId returns a boolean if a field has been set.
func (o *AppLocaleDto) HasLastModifierId() bool {
	if o != nil && o.LastModifierId.IsSet() {
		return true
	}

	return false
}

// SetLastModifierId gets a reference to the given NullableString and assigns it to the LastModifierId field.
func (o *AppLocaleDto) SetLastModifierId(v string) {
	o.LastModifierId.Set(&v)
}
// SetLastModifierIdNil sets the value for LastModifierId to be an explicit nil
func (o *AppLocaleDto) SetLastModifierIdNil() {
	o.LastModifierId.Set(nil)
}

// UnsetLastModifierId ensures that no value is present for LastModifierId, not even an explicit nil
func (o *AppLocaleDto) UnsetLastModifierId() {
	o.LastModifierId.Unset()
}

// GetIsDeleted returns the IsDeleted field value if set, zero value otherwise.
func (o *AppLocaleDto) GetIsDeleted() bool {
	if o == nil || IsNil(o.IsDeleted) {
		var ret bool
		return ret
	}
	return *o.IsDeleted
}

// GetIsDeletedOk returns a tuple with the IsDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppLocaleDto) GetIsDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDeleted) {
		return nil, false
	}
	return o.IsDeleted, true
}

// HasIsDeleted returns a boolean if a field has been set.
func (o *AppLocaleDto) HasIsDeleted() bool {
	if o != nil && !IsNil(o.IsDeleted) {
		return true
	}

	return false
}

// SetIsDeleted gets a reference to the given bool and assigns it to the IsDeleted field.
func (o *AppLocaleDto) SetIsDeleted(v bool) {
	o.IsDeleted = &v
}

// GetDeleterId returns the DeleterId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppLocaleDto) GetDeleterId() string {
	if o == nil || IsNil(o.DeleterId.Get()) {
		var ret string
		return ret
	}
	return *o.DeleterId.Get()
}

// GetDeleterIdOk returns a tuple with the DeleterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppLocaleDto) GetDeleterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeleterId.Get(), o.DeleterId.IsSet()
}

// HasDeleterId returns a boolean if a field has been set.
func (o *AppLocaleDto) HasDeleterId() bool {
	if o != nil && o.DeleterId.IsSet() {
		return true
	}

	return false
}

// SetDeleterId gets a reference to the given NullableString and assigns it to the DeleterId field.
func (o *AppLocaleDto) SetDeleterId(v string) {
	o.DeleterId.Set(&v)
}
// SetDeleterIdNil sets the value for DeleterId to be an explicit nil
func (o *AppLocaleDto) SetDeleterIdNil() {
	o.DeleterId.Set(nil)
}

// UnsetDeleterId ensures that no value is present for DeleterId, not even an explicit nil
func (o *AppLocaleDto) UnsetDeleterId() {
	o.DeleterId.Unset()
}

// GetDeletionTime returns the DeletionTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppLocaleDto) GetDeletionTime() time.Time {
	if o == nil || IsNil(o.DeletionTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.DeletionTime.Get()
}

// GetDeletionTimeOk returns a tuple with the DeletionTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppLocaleDto) GetDeletionTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeletionTime.Get(), o.DeletionTime.IsSet()
}

// HasDeletionTime returns a boolean if a field has been set.
func (o *AppLocaleDto) HasDeletionTime() bool {
	if o != nil && o.DeletionTime.IsSet() {
		return true
	}

	return false
}

// SetDeletionTime gets a reference to the given NullableTime and assigns it to the DeletionTime field.
func (o *AppLocaleDto) SetDeletionTime(v time.Time) {
	o.DeletionTime.Set(&v)
}
// SetDeletionTimeNil sets the value for DeletionTime to be an explicit nil
func (o *AppLocaleDto) SetDeletionTimeNil() {
	o.DeletionTime.Set(nil)
}

// UnsetDeletionTime ensures that no value is present for DeletionTime, not even an explicit nil
func (o *AppLocaleDto) UnsetDeletionTime() {
	o.DeletionTime.Unset()
}

// GetAppId returns the AppId field value if set, zero value otherwise.
func (o *AppLocaleDto) GetAppId() string {
	if o == nil || IsNil(o.AppId) {
		var ret string
		return ret
	}
	return *o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppLocaleDto) GetAppIdOk() (*string, bool) {
	if o == nil || IsNil(o.AppId) {
		return nil, false
	}
	return o.AppId, true
}

// HasAppId returns a boolean if a field has been set.
func (o *AppLocaleDto) HasAppId() bool {
	if o != nil && !IsNil(o.AppId) {
		return true
	}

	return false
}

// SetAppId gets a reference to the given string and assigns it to the AppId field.
func (o *AppLocaleDto) SetAppId(v string) {
	o.AppId = &v
}

// GetLangCode returns the LangCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppLocaleDto) GetLangCode() string {
	if o == nil || IsNil(o.LangCode.Get()) {
		var ret string
		return ret
	}
	return *o.LangCode.Get()
}

// GetLangCodeOk returns a tuple with the LangCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppLocaleDto) GetLangCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LangCode.Get(), o.LangCode.IsSet()
}

// HasLangCode returns a boolean if a field has been set.
func (o *AppLocaleDto) HasLangCode() bool {
	if o != nil && o.LangCode.IsSet() {
		return true
	}

	return false
}

// SetLangCode gets a reference to the given NullableString and assigns it to the LangCode field.
func (o *AppLocaleDto) SetLangCode(v string) {
	o.LangCode.Set(&v)
}
// SetLangCodeNil sets the value for LangCode to be an explicit nil
func (o *AppLocaleDto) SetLangCodeNil() {
	o.LangCode.Set(nil)
}

// UnsetLangCode ensures that no value is present for LangCode, not even an explicit nil
func (o *AppLocaleDto) UnsetLangCode() {
	o.LangCode.Unset()
}

// GetCountryCode returns the CountryCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppLocaleDto) GetCountryCode() string {
	if o == nil || IsNil(o.CountryCode.Get()) {
		var ret string
		return ret
	}
	return *o.CountryCode.Get()
}

// GetCountryCodeOk returns a tuple with the CountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppLocaleDto) GetCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CountryCode.Get(), o.CountryCode.IsSet()
}

// HasCountryCode returns a boolean if a field has been set.
func (o *AppLocaleDto) HasCountryCode() bool {
	if o != nil && o.CountryCode.IsSet() {
		return true
	}

	return false
}

// SetCountryCode gets a reference to the given NullableString and assigns it to the CountryCode field.
func (o *AppLocaleDto) SetCountryCode(v string) {
	o.CountryCode.Set(&v)
}
// SetCountryCodeNil sets the value for CountryCode to be an explicit nil
func (o *AppLocaleDto) SetCountryCodeNil() {
	o.CountryCode.Set(nil)
}

// UnsetCountryCode ensures that no value is present for CountryCode, not even an explicit nil
func (o *AppLocaleDto) UnsetCountryCode() {
	o.CountryCode.Unset()
}

// GetTitle returns the Title field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppLocaleDto) GetTitle() string {
	if o == nil || IsNil(o.Title.Get()) {
		var ret string
		return ret
	}
	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppLocaleDto) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// HasTitle returns a boolean if a field has been set.
func (o *AppLocaleDto) HasTitle() bool {
	if o != nil && o.Title.IsSet() {
		return true
	}

	return false
}

// SetTitle gets a reference to the given NullableString and assigns it to the Title field.
func (o *AppLocaleDto) SetTitle(v string) {
	o.Title.Set(&v)
}
// SetTitleNil sets the value for Title to be an explicit nil
func (o *AppLocaleDto) SetTitleNil() {
	o.Title.Set(nil)
}

// UnsetTitle ensures that no value is present for Title, not even an explicit nil
func (o *AppLocaleDto) UnsetTitle() {
	o.Title.Unset()
}

// GetSubtitle returns the Subtitle field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppLocaleDto) GetSubtitle() string {
	if o == nil || IsNil(o.Subtitle.Get()) {
		var ret string
		return ret
	}
	return *o.Subtitle.Get()
}

// GetSubtitleOk returns a tuple with the Subtitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppLocaleDto) GetSubtitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Subtitle.Get(), o.Subtitle.IsSet()
}

// HasSubtitle returns a boolean if a field has been set.
func (o *AppLocaleDto) HasSubtitle() bool {
	if o != nil && o.Subtitle.IsSet() {
		return true
	}

	return false
}

// SetSubtitle gets a reference to the given NullableString and assigns it to the Subtitle field.
func (o *AppLocaleDto) SetSubtitle(v string) {
	o.Subtitle.Set(&v)
}
// SetSubtitleNil sets the value for Subtitle to be an explicit nil
func (o *AppLocaleDto) SetSubtitleNil() {
	o.Subtitle.Set(nil)
}

// UnsetSubtitle ensures that no value is present for Subtitle, not even an explicit nil
func (o *AppLocaleDto) UnsetSubtitle() {
	o.Subtitle.Unset()
}

// GetShortDesc returns the ShortDesc field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppLocaleDto) GetShortDesc() string {
	if o == nil || IsNil(o.ShortDesc.Get()) {
		var ret string
		return ret
	}
	return *o.ShortDesc.Get()
}

// GetShortDescOk returns a tuple with the ShortDesc field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppLocaleDto) GetShortDescOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShortDesc.Get(), o.ShortDesc.IsSet()
}

// HasShortDesc returns a boolean if a field has been set.
func (o *AppLocaleDto) HasShortDesc() bool {
	if o != nil && o.ShortDesc.IsSet() {
		return true
	}

	return false
}

// SetShortDesc gets a reference to the given NullableString and assigns it to the ShortDesc field.
func (o *AppLocaleDto) SetShortDesc(v string) {
	o.ShortDesc.Set(&v)
}
// SetShortDescNil sets the value for ShortDesc to be an explicit nil
func (o *AppLocaleDto) SetShortDescNil() {
	o.ShortDesc.Set(nil)
}

// UnsetShortDesc ensures that no value is present for ShortDesc, not even an explicit nil
func (o *AppLocaleDto) UnsetShortDesc() {
	o.ShortDesc.Unset()
}

// GetFullDesc returns the FullDesc field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppLocaleDto) GetFullDesc() string {
	if o == nil || IsNil(o.FullDesc.Get()) {
		var ret string
		return ret
	}
	return *o.FullDesc.Get()
}

// GetFullDescOk returns a tuple with the FullDesc field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppLocaleDto) GetFullDescOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FullDesc.Get(), o.FullDesc.IsSet()
}

// HasFullDesc returns a boolean if a field has been set.
func (o *AppLocaleDto) HasFullDesc() bool {
	if o != nil && o.FullDesc.IsSet() {
		return true
	}

	return false
}

// SetFullDesc gets a reference to the given NullableString and assigns it to the FullDesc field.
func (o *AppLocaleDto) SetFullDesc(v string) {
	o.FullDesc.Set(&v)
}
// SetFullDescNil sets the value for FullDesc to be an explicit nil
func (o *AppLocaleDto) SetFullDescNil() {
	o.FullDesc.Set(nil)
}

// UnsetFullDesc ensures that no value is present for FullDesc, not even an explicit nil
func (o *AppLocaleDto) UnsetFullDesc() {
	o.FullDesc.Unset()
}

// GetKeywords returns the Keywords field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppLocaleDto) GetKeywords() string {
	if o == nil || IsNil(o.Keywords.Get()) {
		var ret string
		return ret
	}
	return *o.Keywords.Get()
}

// GetKeywordsOk returns a tuple with the Keywords field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppLocaleDto) GetKeywordsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Keywords.Get(), o.Keywords.IsSet()
}

// HasKeywords returns a boolean if a field has been set.
func (o *AppLocaleDto) HasKeywords() bool {
	if o != nil && o.Keywords.IsSet() {
		return true
	}

	return false
}

// SetKeywords gets a reference to the given NullableString and assigns it to the Keywords field.
func (o *AppLocaleDto) SetKeywords(v string) {
	o.Keywords.Set(&v)
}
// SetKeywordsNil sets the value for Keywords to be an explicit nil
func (o *AppLocaleDto) SetKeywordsNil() {
	o.Keywords.Set(nil)
}

// UnsetKeywords ensures that no value is present for Keywords, not even an explicit nil
func (o *AppLocaleDto) UnsetKeywords() {
	o.Keywords.Unset()
}

// GetPromoText returns the PromoText field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppLocaleDto) GetPromoText() string {
	if o == nil || IsNil(o.PromoText.Get()) {
		var ret string
		return ret
	}
	return *o.PromoText.Get()
}

// GetPromoTextOk returns a tuple with the PromoText field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppLocaleDto) GetPromoTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PromoText.Get(), o.PromoText.IsSet()
}

// HasPromoText returns a boolean if a field has been set.
func (o *AppLocaleDto) HasPromoText() bool {
	if o != nil && o.PromoText.IsSet() {
		return true
	}

	return false
}

// SetPromoText gets a reference to the given NullableString and assigns it to the PromoText field.
func (o *AppLocaleDto) SetPromoText(v string) {
	o.PromoText.Set(&v)
}
// SetPromoTextNil sets the value for PromoText to be an explicit nil
func (o *AppLocaleDto) SetPromoTextNil() {
	o.PromoText.Set(nil)
}

// UnsetPromoText ensures that no value is present for PromoText, not even an explicit nil
func (o *AppLocaleDto) UnsetPromoText() {
	o.PromoText.Unset()
}

// GetSupportUrl returns the SupportUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppLocaleDto) GetSupportUrl() string {
	if o == nil || IsNil(o.SupportUrl.Get()) {
		var ret string
		return ret
	}
	return *o.SupportUrl.Get()
}

// GetSupportUrlOk returns a tuple with the SupportUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppLocaleDto) GetSupportUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SupportUrl.Get(), o.SupportUrl.IsSet()
}

// HasSupportUrl returns a boolean if a field has been set.
func (o *AppLocaleDto) HasSupportUrl() bool {
	if o != nil && o.SupportUrl.IsSet() {
		return true
	}

	return false
}

// SetSupportUrl gets a reference to the given NullableString and assigns it to the SupportUrl field.
func (o *AppLocaleDto) SetSupportUrl(v string) {
	o.SupportUrl.Set(&v)
}
// SetSupportUrlNil sets the value for SupportUrl to be an explicit nil
func (o *AppLocaleDto) SetSupportUrlNil() {
	o.SupportUrl.Set(nil)
}

// UnsetSupportUrl ensures that no value is present for SupportUrl, not even an explicit nil
func (o *AppLocaleDto) UnsetSupportUrl() {
	o.SupportUrl.Unset()
}

// GetPrivacyUrl returns the PrivacyUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppLocaleDto) GetPrivacyUrl() string {
	if o == nil || IsNil(o.PrivacyUrl.Get()) {
		var ret string
		return ret
	}
	return *o.PrivacyUrl.Get()
}

// GetPrivacyUrlOk returns a tuple with the PrivacyUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppLocaleDto) GetPrivacyUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrivacyUrl.Get(), o.PrivacyUrl.IsSet()
}

// HasPrivacyUrl returns a boolean if a field has been set.
func (o *AppLocaleDto) HasPrivacyUrl() bool {
	if o != nil && o.PrivacyUrl.IsSet() {
		return true
	}

	return false
}

// SetPrivacyUrl gets a reference to the given NullableString and assigns it to the PrivacyUrl field.
func (o *AppLocaleDto) SetPrivacyUrl(v string) {
	o.PrivacyUrl.Set(&v)
}
// SetPrivacyUrlNil sets the value for PrivacyUrl to be an explicit nil
func (o *AppLocaleDto) SetPrivacyUrlNil() {
	o.PrivacyUrl.Set(nil)
}

// UnsetPrivacyUrl ensures that no value is present for PrivacyUrl, not even an explicit nil
func (o *AppLocaleDto) UnsetPrivacyUrl() {
	o.PrivacyUrl.Unset()
}

// GetReleaseNote returns the ReleaseNote field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppLocaleDto) GetReleaseNote() string {
	if o == nil || IsNil(o.ReleaseNote.Get()) {
		var ret string
		return ret
	}
	return *o.ReleaseNote.Get()
}

// GetReleaseNoteOk returns a tuple with the ReleaseNote field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppLocaleDto) GetReleaseNoteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReleaseNote.Get(), o.ReleaseNote.IsSet()
}

// HasReleaseNote returns a boolean if a field has been set.
func (o *AppLocaleDto) HasReleaseNote() bool {
	if o != nil && o.ReleaseNote.IsSet() {
		return true
	}

	return false
}

// SetReleaseNote gets a reference to the given NullableString and assigns it to the ReleaseNote field.
func (o *AppLocaleDto) SetReleaseNote(v string) {
	o.ReleaseNote.Set(&v)
}
// SetReleaseNoteNil sets the value for ReleaseNote to be an explicit nil
func (o *AppLocaleDto) SetReleaseNoteNil() {
	o.ReleaseNote.Set(nil)
}

// UnsetReleaseNote ensures that no value is present for ReleaseNote, not even an explicit nil
func (o *AppLocaleDto) UnsetReleaseNote() {
	o.ReleaseNote.Unset()
}

func (o AppLocaleDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppLocaleDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CreationTime) {
		toSerialize["creationTime"] = o.CreationTime
	}
	if o.CreatorId.IsSet() {
		toSerialize["creatorId"] = o.CreatorId.Get()
	}
	if o.LastModificationTime.IsSet() {
		toSerialize["lastModificationTime"] = o.LastModificationTime.Get()
	}
	if o.LastModifierId.IsSet() {
		toSerialize["lastModifierId"] = o.LastModifierId.Get()
	}
	if !IsNil(o.IsDeleted) {
		toSerialize["isDeleted"] = o.IsDeleted
	}
	if o.DeleterId.IsSet() {
		toSerialize["deleterId"] = o.DeleterId.Get()
	}
	if o.DeletionTime.IsSet() {
		toSerialize["deletionTime"] = o.DeletionTime.Get()
	}
	if !IsNil(o.AppId) {
		toSerialize["appId"] = o.AppId
	}
	if o.LangCode.IsSet() {
		toSerialize["langCode"] = o.LangCode.Get()
	}
	if o.CountryCode.IsSet() {
		toSerialize["countryCode"] = o.CountryCode.Get()
	}
	if o.Title.IsSet() {
		toSerialize["title"] = o.Title.Get()
	}
	if o.Subtitle.IsSet() {
		toSerialize["subtitle"] = o.Subtitle.Get()
	}
	if o.ShortDesc.IsSet() {
		toSerialize["shortDesc"] = o.ShortDesc.Get()
	}
	if o.FullDesc.IsSet() {
		toSerialize["fullDesc"] = o.FullDesc.Get()
	}
	if o.Keywords.IsSet() {
		toSerialize["keywords"] = o.Keywords.Get()
	}
	if o.PromoText.IsSet() {
		toSerialize["promoText"] = o.PromoText.Get()
	}
	if o.SupportUrl.IsSet() {
		toSerialize["supportUrl"] = o.SupportUrl.Get()
	}
	if o.PrivacyUrl.IsSet() {
		toSerialize["privacyUrl"] = o.PrivacyUrl.Get()
	}
	if o.ReleaseNote.IsSet() {
		toSerialize["releaseNote"] = o.ReleaseNote.Get()
	}
	return toSerialize, nil
}

type NullableAppLocaleDto struct {
	value *AppLocaleDto
	isSet bool
}

func (v NullableAppLocaleDto) Get() *AppLocaleDto {
	return v.value
}

func (v *NullableAppLocaleDto) Set(val *AppLocaleDto) {
	v.value = val
	v.isSet = true
}

func (v NullableAppLocaleDto) IsSet() bool {
	return v.isSet
}

func (v *NullableAppLocaleDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppLocaleDto(val *AppLocaleDto) *NullableAppLocaleDto {
	return &NullableAppLocaleDto{value: val, isSet: true}
}

func (v NullableAppLocaleDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppLocaleDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


