/*
Felorx API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package felorx

import (
	"encoding/json"
	"fmt"
)

// AppFeedbackType 应用反馈类型
type AppFeedbackType string

// List of AppFeedbackType
const (
	APPFEEDBACKTYPE_ISSUE      AppFeedbackType = "Issue"
	APPFEEDBACKTYPE_SUGGESTION AppFeedbackType = "Suggestion"
	APPFEEDBACKTYPE_OTHER      AppFeedbackType = "Other"
)

// All allowed values of AppFeedbackType enum
var AllowedAppFeedbackTypeEnumValues = []AppFeedbackType{
	"Issue",
	"Suggestion",
	"Other",
}

func (v *AppFeedbackType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AppFeedbackType(value)
	for _, existing := range AllowedAppFeedbackTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AppFeedbackType", value)
}

// NewAppFeedbackTypeFromValue returns a pointer to a valid AppFeedbackType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAppFeedbackTypeFromValue(v string) (*AppFeedbackType, error) {
	ev := AppFeedbackType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AppFeedbackType: valid values are %v", v, AllowedAppFeedbackTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AppFeedbackType) IsValid() bool {
	for _, existing := range AllowedAppFeedbackTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AppFeedbackType value
func (v AppFeedbackType) Ptr() *AppFeedbackType {
	return &v
}

type NullableAppFeedbackType struct {
	value *AppFeedbackType
	isSet bool
}

func (v NullableAppFeedbackType) Get() *AppFeedbackType {
	return v.value
}

func (v *NullableAppFeedbackType) Set(val *AppFeedbackType) {
	v.value = val
	v.isSet = true
}

func (v NullableAppFeedbackType) IsSet() bool {
	return v.isSet
}

func (v *NullableAppFeedbackType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppFeedbackType(val *AppFeedbackType) *NullableAppFeedbackType {
	return &NullableAppFeedbackType{value: val, isSet: true}
}

func (v NullableAppFeedbackType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppFeedbackType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
