/*
Felorx API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package felorx

import (
	"encoding/json"
	"time"
)

// checks if the AiUsageSummaryDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AiUsageSummaryDto{}

// AiUsageSummaryDto struct for AiUsageSummaryDto
type AiUsageSummaryDto struct {
	From *time.Time `json:"from,omitempty"`
	To *time.Time `json:"to,omitempty"`
	ModelUsages []AiModelUsageDto `json:"model_usages,omitempty"`
	RuntimeUsages []interface{} `json:"runtime_usages,omitempty"`
}

// NewAiUsageSummaryDto instantiates a new AiUsageSummaryDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAiUsageSummaryDto() *AiUsageSummaryDto {
	this := AiUsageSummaryDto{}
	return &this
}

// NewAiUsageSummaryDtoWithDefaults instantiates a new AiUsageSummaryDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAiUsageSummaryDtoWithDefaults() *AiUsageSummaryDto {
	this := AiUsageSummaryDto{}
	return &this
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *AiUsageSummaryDto) GetFrom() time.Time {
	if o == nil || IsNil(o.From) {
		var ret time.Time
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiUsageSummaryDto) GetFromOk() (*time.Time, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *AiUsageSummaryDto) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given time.Time and assigns it to the From field.
func (o *AiUsageSummaryDto) SetFrom(v time.Time) {
	o.From = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *AiUsageSummaryDto) GetTo() time.Time {
	if o == nil || IsNil(o.To) {
		var ret time.Time
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiUsageSummaryDto) GetToOk() (*time.Time, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *AiUsageSummaryDto) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given time.Time and assigns it to the To field.
func (o *AiUsageSummaryDto) SetTo(v time.Time) {
	o.To = &v
}

// GetModelUsages returns the ModelUsages field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AiUsageSummaryDto) GetModelUsages() []AiModelUsageDto {
	if o == nil {
		var ret []AiModelUsageDto
		return ret
	}
	return o.ModelUsages
}

// GetModelUsagesOk returns a tuple with the ModelUsages field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AiUsageSummaryDto) GetModelUsagesOk() ([]AiModelUsageDto, bool) {
	if o == nil || IsNil(o.ModelUsages) {
		return nil, false
	}
	return o.ModelUsages, true
}

// HasModelUsages returns a boolean if a field has been set.
func (o *AiUsageSummaryDto) HasModelUsages() bool {
	if o != nil && !IsNil(o.ModelUsages) {
		return true
	}

	return false
}

// SetModelUsages gets a reference to the given []AiModelUsageDto and assigns it to the ModelUsages field.
func (o *AiUsageSummaryDto) SetModelUsages(v []AiModelUsageDto) {
	o.ModelUsages = v
}

// GetRuntimeUsages returns the RuntimeUsages field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AiUsageSummaryDto) GetRuntimeUsages() []interface{} {
	if o == nil {
		var ret []interface{}
		return ret
	}
	return o.RuntimeUsages
}

// GetRuntimeUsagesOk returns a tuple with the RuntimeUsages field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AiUsageSummaryDto) GetRuntimeUsagesOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.RuntimeUsages) {
		return nil, false
	}
	return o.RuntimeUsages, true
}

// HasRuntimeUsages returns a boolean if a field has been set.
func (o *AiUsageSummaryDto) HasRuntimeUsages() bool {
	if o != nil && !IsNil(o.RuntimeUsages) {
		return true
	}

	return false
}

// SetRuntimeUsages gets a reference to the given []interface{} and assigns it to the RuntimeUsages field.
func (o *AiUsageSummaryDto) SetRuntimeUsages(v []interface{}) {
	o.RuntimeUsages = v
}

func (o AiUsageSummaryDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AiUsageSummaryDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	if o.ModelUsages != nil {
		toSerialize["model_usages"] = o.ModelUsages
	}
	if o.RuntimeUsages != nil {
		toSerialize["runtime_usages"] = o.RuntimeUsages
	}
	return toSerialize, nil
}

type NullableAiUsageSummaryDto struct {
	value *AiUsageSummaryDto
	isSet bool
}

func (v NullableAiUsageSummaryDto) Get() *AiUsageSummaryDto {
	return v.value
}

func (v *NullableAiUsageSummaryDto) Set(val *AiUsageSummaryDto) {
	v.value = val
	v.isSet = true
}

func (v NullableAiUsageSummaryDto) IsSet() bool {
	return v.isSet
}

func (v *NullableAiUsageSummaryDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAiUsageSummaryDto(val *AiUsageSummaryDto) *NullableAiUsageSummaryDto {
	return &NullableAiUsageSummaryDto{value: val, isSet: true}
}

func (v NullableAiUsageSummaryDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAiUsageSummaryDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


