/*
Felorx API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package felorx

import (
	"encoding/json"
	"time"
)

// checks if the RemotePairingAssertionDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemotePairingAssertionDto{}

// RemotePairingAssertionDto struct for RemotePairingAssertionDto
type RemotePairingAssertionDto struct {
	Assertion NullableString `json:"assertion,omitempty"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
}

// NewRemotePairingAssertionDto instantiates a new RemotePairingAssertionDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemotePairingAssertionDto() *RemotePairingAssertionDto {
	this := RemotePairingAssertionDto{}
	return &this
}

// NewRemotePairingAssertionDtoWithDefaults instantiates a new RemotePairingAssertionDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemotePairingAssertionDtoWithDefaults() *RemotePairingAssertionDto {
	this := RemotePairingAssertionDto{}
	return &this
}

// GetAssertion returns the Assertion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RemotePairingAssertionDto) GetAssertion() string {
	if o == nil || IsNil(o.Assertion.Get()) {
		var ret string
		return ret
	}
	return *o.Assertion.Get()
}

// GetAssertionOk returns a tuple with the Assertion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RemotePairingAssertionDto) GetAssertionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Assertion.Get(), o.Assertion.IsSet()
}

// HasAssertion returns a boolean if a field has been set.
func (o *RemotePairingAssertionDto) HasAssertion() bool {
	if o != nil && o.Assertion.IsSet() {
		return true
	}

	return false
}

// SetAssertion gets a reference to the given NullableString and assigns it to the Assertion field.
func (o *RemotePairingAssertionDto) SetAssertion(v string) {
	o.Assertion.Set(&v)
}
// SetAssertionNil sets the value for Assertion to be an explicit nil
func (o *RemotePairingAssertionDto) SetAssertionNil() {
	o.Assertion.Set(nil)
}

// UnsetAssertion ensures that no value is present for Assertion, not even an explicit nil
func (o *RemotePairingAssertionDto) UnsetAssertion() {
	o.Assertion.Unset()
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *RemotePairingAssertionDto) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemotePairingAssertionDto) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *RemotePairingAssertionDto) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *RemotePairingAssertionDto) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

func (o RemotePairingAssertionDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemotePairingAssertionDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Assertion.IsSet() {
		toSerialize["assertion"] = o.Assertion.Get()
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expiresAt"] = o.ExpiresAt
	}
	return toSerialize, nil
}

type NullableRemotePairingAssertionDto struct {
	value *RemotePairingAssertionDto
	isSet bool
}

func (v NullableRemotePairingAssertionDto) Get() *RemotePairingAssertionDto {
	return v.value
}

func (v *NullableRemotePairingAssertionDto) Set(val *RemotePairingAssertionDto) {
	v.value = val
	v.isSet = true
}

func (v NullableRemotePairingAssertionDto) IsSet() bool {
	return v.isSet
}

func (v *NullableRemotePairingAssertionDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemotePairingAssertionDto(val *RemotePairingAssertionDto) *NullableRemotePairingAssertionDto {
	return &NullableRemotePairingAssertionDto{value: val, isSet: true}
}

func (v NullableRemotePairingAssertionDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemotePairingAssertionDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


