/*
Felorx API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package felorx

import (
	"encoding/json"
)

// checks if the MessageRecallDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageRecallDto{}

// MessageRecallDto struct for MessageRecallDto
type MessageRecallDto struct {
	FelorxId *string `json:"felorxId,omitempty"`
}

// NewMessageRecallDto instantiates a new MessageRecallDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageRecallDto() *MessageRecallDto {
	this := MessageRecallDto{}
	return &this
}

// NewMessageRecallDtoWithDefaults instantiates a new MessageRecallDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageRecallDtoWithDefaults() *MessageRecallDto {
	this := MessageRecallDto{}
	return &this
}

// GetFelorxId returns the FelorxId field value if set, zero value otherwise.
func (o *MessageRecallDto) GetFelorxId() string {
	if o == nil || IsNil(o.FelorxId) {
		var ret string
		return ret
	}
	return *o.FelorxId
}

// GetFelorxIdOk returns a tuple with the FelorxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageRecallDto) GetFelorxIdOk() (*string, bool) {
	if o == nil || IsNil(o.FelorxId) {
		return nil, false
	}
	return o.FelorxId, true
}

// HasFelorxId returns a boolean if a field has been set.
func (o *MessageRecallDto) HasFelorxId() bool {
	if o != nil && !IsNil(o.FelorxId) {
		return true
	}

	return false
}

// SetFelorxId gets a reference to the given string and assigns it to the FelorxId field.
func (o *MessageRecallDto) SetFelorxId(v string) {
	o.FelorxId = &v
}

func (o MessageRecallDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageRecallDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FelorxId) {
		toSerialize["felorxId"] = o.FelorxId
	}
	return toSerialize, nil
}

type NullableMessageRecallDto struct {
	value *MessageRecallDto
	isSet bool
}

func (v NullableMessageRecallDto) Get() *MessageRecallDto {
	return v.value
}

func (v *NullableMessageRecallDto) Set(val *MessageRecallDto) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageRecallDto) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageRecallDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageRecallDto(val *MessageRecallDto) *NullableMessageRecallDto {
	return &NullableMessageRecallDto{value: val, isSet: true}
}

func (v NullableMessageRecallDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageRecallDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
