/*
Felorx API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package felorx

import (
	"encoding/json"
	"fmt"
)

// AppAssetDeviceType 素材面向的设备类型（可空表示不限；JSON / 数据库存储均为枚举名字符串）。
type AppAssetDeviceType string

// List of AppAssetDeviceType
const (
	APPASSETDEVICETYPE_PHONE   AppAssetDeviceType = "Phone"
	APPASSETDEVICETYPE_PAD     AppAssetDeviceType = "Pad"
	APPASSETDEVICETYPE_TV      AppAssetDeviceType = "Tv"
	APPASSETDEVICETYPE_DESKTOP AppAssetDeviceType = "Desktop"
)

// All allowed values of AppAssetDeviceType enum
var AllowedAppAssetDeviceTypeEnumValues = []AppAssetDeviceType{
	"Phone",
	"Pad",
	"Tv",
	"Desktop",
}

func (v *AppAssetDeviceType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AppAssetDeviceType(value)
	for _, existing := range AllowedAppAssetDeviceTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AppAssetDeviceType", value)
}

// NewAppAssetDeviceTypeFromValue returns a pointer to a valid AppAssetDeviceType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAppAssetDeviceTypeFromValue(v string) (*AppAssetDeviceType, error) {
	ev := AppAssetDeviceType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AppAssetDeviceType: valid values are %v", v, AllowedAppAssetDeviceTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AppAssetDeviceType) IsValid() bool {
	for _, existing := range AllowedAppAssetDeviceTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AppAssetDeviceType value
func (v AppAssetDeviceType) Ptr() *AppAssetDeviceType {
	return &v
}

type NullableAppAssetDeviceType struct {
	value *AppAssetDeviceType
	isSet bool
}

func (v NullableAppAssetDeviceType) Get() *AppAssetDeviceType {
	return v.value
}

func (v *NullableAppAssetDeviceType) Set(val *AppAssetDeviceType) {
	v.value = val
	v.isSet = true
}

func (v NullableAppAssetDeviceType) IsSet() bool {
	return v.isSet
}

func (v *NullableAppAssetDeviceType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppAssetDeviceType(val *AppAssetDeviceType) *NullableAppAssetDeviceType {
	return &NullableAppAssetDeviceType{value: val, isSet: true}
}

func (v NullableAppAssetDeviceType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppAssetDeviceType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
