/*
Felorx API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package felorx

import (
	"encoding/json"
	"time"
)

// checks if the ApiKeyDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiKeyDto{}

// ApiKeyDto struct for ApiKeyDto
type ApiKeyDto struct {
	Id       *string        `json:"id,omitempty"`
	Name     NullableString `json:"name,omitempty"`
	Key      NullableString `json:"key,omitempty"`
	Active   *bool          `json:"active,omitempty"`
	ExpireAt NullableTime   `json:"expireAt,omitempty"`
}

// NewApiKeyDto instantiates a new ApiKeyDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiKeyDto() *ApiKeyDto {
	this := ApiKeyDto{}
	return &this
}

// NewApiKeyDtoWithDefaults instantiates a new ApiKeyDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiKeyDtoWithDefaults() *ApiKeyDto {
	this := ApiKeyDto{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApiKeyDto) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiKeyDto) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApiKeyDto) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ApiKeyDto) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiKeyDto) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiKeyDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ApiKeyDto) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ApiKeyDto) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *ApiKeyDto) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ApiKeyDto) UnsetName() {
	o.Name.Unset()
}

// GetKey returns the Key field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiKeyDto) GetKey() string {
	if o == nil || IsNil(o.Key.Get()) {
		var ret string
		return ret
	}
	return *o.Key.Get()
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiKeyDto) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Key.Get(), o.Key.IsSet()
}

// HasKey returns a boolean if a field has been set.
func (o *ApiKeyDto) HasKey() bool {
	if o != nil && o.Key.IsSet() {
		return true
	}

	return false
}

// SetKey gets a reference to the given NullableString and assigns it to the Key field.
func (o *ApiKeyDto) SetKey(v string) {
	o.Key.Set(&v)
}

// SetKeyNil sets the value for Key to be an explicit nil
func (o *ApiKeyDto) SetKeyNil() {
	o.Key.Set(nil)
}

// UnsetKey ensures that no value is present for Key, not even an explicit nil
func (o *ApiKeyDto) UnsetKey() {
	o.Key.Unset()
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *ApiKeyDto) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiKeyDto) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *ApiKeyDto) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *ApiKeyDto) SetActive(v bool) {
	o.Active = &v
}

// GetExpireAt returns the ExpireAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiKeyDto) GetExpireAt() time.Time {
	if o == nil || IsNil(o.ExpireAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ExpireAt.Get()
}

// GetExpireAtOk returns a tuple with the ExpireAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiKeyDto) GetExpireAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpireAt.Get(), o.ExpireAt.IsSet()
}

// HasExpireAt returns a boolean if a field has been set.
func (o *ApiKeyDto) HasExpireAt() bool {
	if o != nil && o.ExpireAt.IsSet() {
		return true
	}

	return false
}

// SetExpireAt gets a reference to the given NullableTime and assigns it to the ExpireAt field.
func (o *ApiKeyDto) SetExpireAt(v time.Time) {
	o.ExpireAt.Set(&v)
}

// SetExpireAtNil sets the value for ExpireAt to be an explicit nil
func (o *ApiKeyDto) SetExpireAtNil() {
	o.ExpireAt.Set(nil)
}

// UnsetExpireAt ensures that no value is present for ExpireAt, not even an explicit nil
func (o *ApiKeyDto) UnsetExpireAt() {
	o.ExpireAt.Unset()
}

func (o ApiKeyDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiKeyDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Key.IsSet() {
		toSerialize["key"] = o.Key.Get()
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if o.ExpireAt.IsSet() {
		toSerialize["expireAt"] = o.ExpireAt.Get()
	}
	return toSerialize, nil
}

type NullableApiKeyDto struct {
	value *ApiKeyDto
	isSet bool
}

func (v NullableApiKeyDto) Get() *ApiKeyDto {
	return v.value
}

func (v *NullableApiKeyDto) Set(val *ApiKeyDto) {
	v.value = val
	v.isSet = true
}

func (v NullableApiKeyDto) IsSet() bool {
	return v.isSet
}

func (v *NullableApiKeyDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiKeyDto(val *ApiKeyDto) *NullableApiKeyDto {
	return &NullableApiKeyDto{value: val, isSet: true}
}

func (v NullableApiKeyDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiKeyDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
