/*
Felorx API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package felorx

import (
	"encoding/json"
)

// checks if the OpsCryptoVaultDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpsCryptoVaultDto{}

// OpsCryptoVaultDto struct for OpsCryptoVaultDto
type OpsCryptoVaultDto struct {
	SaltBase64 NullableString `json:"saltBase64,omitempty"`
	WrappedUserKeyJson NullableString `json:"wrappedUserKeyJson,omitempty"`
	PublicKeyJwkJson NullableString `json:"publicKeyJwkJson,omitempty"`
	WrappedRsaPrivateJson NullableString `json:"wrappedRsaPrivateJson,omitempty"`
}

// NewOpsCryptoVaultDto instantiates a new OpsCryptoVaultDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpsCryptoVaultDto() *OpsCryptoVaultDto {
	this := OpsCryptoVaultDto{}
	return &this
}

// NewOpsCryptoVaultDtoWithDefaults instantiates a new OpsCryptoVaultDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpsCryptoVaultDtoWithDefaults() *OpsCryptoVaultDto {
	this := OpsCryptoVaultDto{}
	return &this
}

// GetSaltBase64 returns the SaltBase64 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpsCryptoVaultDto) GetSaltBase64() string {
	if o == nil || IsNil(o.SaltBase64.Get()) {
		var ret string
		return ret
	}
	return *o.SaltBase64.Get()
}

// GetSaltBase64Ok returns a tuple with the SaltBase64 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpsCryptoVaultDto) GetSaltBase64Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SaltBase64.Get(), o.SaltBase64.IsSet()
}

// HasSaltBase64 returns a boolean if a field has been set.
func (o *OpsCryptoVaultDto) HasSaltBase64() bool {
	if o != nil && o.SaltBase64.IsSet() {
		return true
	}

	return false
}

// SetSaltBase64 gets a reference to the given NullableString and assigns it to the SaltBase64 field.
func (o *OpsCryptoVaultDto) SetSaltBase64(v string) {
	o.SaltBase64.Set(&v)
}
// SetSaltBase64Nil sets the value for SaltBase64 to be an explicit nil
func (o *OpsCryptoVaultDto) SetSaltBase64Nil() {
	o.SaltBase64.Set(nil)
}

// UnsetSaltBase64 ensures that no value is present for SaltBase64, not even an explicit nil
func (o *OpsCryptoVaultDto) UnsetSaltBase64() {
	o.SaltBase64.Unset()
}

// GetWrappedUserKeyJson returns the WrappedUserKeyJson field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpsCryptoVaultDto) GetWrappedUserKeyJson() string {
	if o == nil || IsNil(o.WrappedUserKeyJson.Get()) {
		var ret string
		return ret
	}
	return *o.WrappedUserKeyJson.Get()
}

// GetWrappedUserKeyJsonOk returns a tuple with the WrappedUserKeyJson field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpsCryptoVaultDto) GetWrappedUserKeyJsonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WrappedUserKeyJson.Get(), o.WrappedUserKeyJson.IsSet()
}

// HasWrappedUserKeyJson returns a boolean if a field has been set.
func (o *OpsCryptoVaultDto) HasWrappedUserKeyJson() bool {
	if o != nil && o.WrappedUserKeyJson.IsSet() {
		return true
	}

	return false
}

// SetWrappedUserKeyJson gets a reference to the given NullableString and assigns it to the WrappedUserKeyJson field.
func (o *OpsCryptoVaultDto) SetWrappedUserKeyJson(v string) {
	o.WrappedUserKeyJson.Set(&v)
}
// SetWrappedUserKeyJsonNil sets the value for WrappedUserKeyJson to be an explicit nil
func (o *OpsCryptoVaultDto) SetWrappedUserKeyJsonNil() {
	o.WrappedUserKeyJson.Set(nil)
}

// UnsetWrappedUserKeyJson ensures that no value is present for WrappedUserKeyJson, not even an explicit nil
func (o *OpsCryptoVaultDto) UnsetWrappedUserKeyJson() {
	o.WrappedUserKeyJson.Unset()
}

// GetPublicKeyJwkJson returns the PublicKeyJwkJson field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpsCryptoVaultDto) GetPublicKeyJwkJson() string {
	if o == nil || IsNil(o.PublicKeyJwkJson.Get()) {
		var ret string
		return ret
	}
	return *o.PublicKeyJwkJson.Get()
}

// GetPublicKeyJwkJsonOk returns a tuple with the PublicKeyJwkJson field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpsCryptoVaultDto) GetPublicKeyJwkJsonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PublicKeyJwkJson.Get(), o.PublicKeyJwkJson.IsSet()
}

// HasPublicKeyJwkJson returns a boolean if a field has been set.
func (o *OpsCryptoVaultDto) HasPublicKeyJwkJson() bool {
	if o != nil && o.PublicKeyJwkJson.IsSet() {
		return true
	}

	return false
}

// SetPublicKeyJwkJson gets a reference to the given NullableString and assigns it to the PublicKeyJwkJson field.
func (o *OpsCryptoVaultDto) SetPublicKeyJwkJson(v string) {
	o.PublicKeyJwkJson.Set(&v)
}
// SetPublicKeyJwkJsonNil sets the value for PublicKeyJwkJson to be an explicit nil
func (o *OpsCryptoVaultDto) SetPublicKeyJwkJsonNil() {
	o.PublicKeyJwkJson.Set(nil)
}

// UnsetPublicKeyJwkJson ensures that no value is present for PublicKeyJwkJson, not even an explicit nil
func (o *OpsCryptoVaultDto) UnsetPublicKeyJwkJson() {
	o.PublicKeyJwkJson.Unset()
}

// GetWrappedRsaPrivateJson returns the WrappedRsaPrivateJson field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpsCryptoVaultDto) GetWrappedRsaPrivateJson() string {
	if o == nil || IsNil(o.WrappedRsaPrivateJson.Get()) {
		var ret string
		return ret
	}
	return *o.WrappedRsaPrivateJson.Get()
}

// GetWrappedRsaPrivateJsonOk returns a tuple with the WrappedRsaPrivateJson field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpsCryptoVaultDto) GetWrappedRsaPrivateJsonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WrappedRsaPrivateJson.Get(), o.WrappedRsaPrivateJson.IsSet()
}

// HasWrappedRsaPrivateJson returns a boolean if a field has been set.
func (o *OpsCryptoVaultDto) HasWrappedRsaPrivateJson() bool {
	if o != nil && o.WrappedRsaPrivateJson.IsSet() {
		return true
	}

	return false
}

// SetWrappedRsaPrivateJson gets a reference to the given NullableString and assigns it to the WrappedRsaPrivateJson field.
func (o *OpsCryptoVaultDto) SetWrappedRsaPrivateJson(v string) {
	o.WrappedRsaPrivateJson.Set(&v)
}
// SetWrappedRsaPrivateJsonNil sets the value for WrappedRsaPrivateJson to be an explicit nil
func (o *OpsCryptoVaultDto) SetWrappedRsaPrivateJsonNil() {
	o.WrappedRsaPrivateJson.Set(nil)
}

// UnsetWrappedRsaPrivateJson ensures that no value is present for WrappedRsaPrivateJson, not even an explicit nil
func (o *OpsCryptoVaultDto) UnsetWrappedRsaPrivateJson() {
	o.WrappedRsaPrivateJson.Unset()
}

func (o OpsCryptoVaultDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpsCryptoVaultDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.SaltBase64.IsSet() {
		toSerialize["saltBase64"] = o.SaltBase64.Get()
	}
	if o.WrappedUserKeyJson.IsSet() {
		toSerialize["wrappedUserKeyJson"] = o.WrappedUserKeyJson.Get()
	}
	if o.PublicKeyJwkJson.IsSet() {
		toSerialize["publicKeyJwkJson"] = o.PublicKeyJwkJson.Get()
	}
	if o.WrappedRsaPrivateJson.IsSet() {
		toSerialize["wrappedRsaPrivateJson"] = o.WrappedRsaPrivateJson.Get()
	}
	return toSerialize, nil
}

type NullableOpsCryptoVaultDto struct {
	value *OpsCryptoVaultDto
	isSet bool
}

func (v NullableOpsCryptoVaultDto) Get() *OpsCryptoVaultDto {
	return v.value
}

func (v *NullableOpsCryptoVaultDto) Set(val *OpsCryptoVaultDto) {
	v.value = val
	v.isSet = true
}

func (v NullableOpsCryptoVaultDto) IsSet() bool {
	return v.isSet
}

func (v *NullableOpsCryptoVaultDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpsCryptoVaultDto(val *OpsCryptoVaultDto) *NullableOpsCryptoVaultDto {
	return &NullableOpsCryptoVaultDto{value: val, isSet: true}
}

func (v NullableOpsCryptoVaultDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpsCryptoVaultDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


