/*
Felorx API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package felorx

import (
	"encoding/json"
)

// checks if the AiUsageDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AiUsageDto{}

// AiUsageDto struct for AiUsageDto
type AiUsageDto struct {
	PromptTokens NullableInt32 `json:"prompt_tokens,omitempty"`
	CompletionTokens NullableInt32 `json:"completion_tokens,omitempty"`
	TotalTokens NullableInt32 `json:"total_tokens,omitempty"`
}

// NewAiUsageDto instantiates a new AiUsageDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAiUsageDto() *AiUsageDto {
	this := AiUsageDto{}
	return &this
}

// NewAiUsageDtoWithDefaults instantiates a new AiUsageDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAiUsageDtoWithDefaults() *AiUsageDto {
	this := AiUsageDto{}
	return &this
}

// GetPromptTokens returns the PromptTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AiUsageDto) GetPromptTokens() int32 {
	if o == nil || IsNil(o.PromptTokens.Get()) {
		var ret int32
		return ret
	}
	return *o.PromptTokens.Get()
}

// GetPromptTokensOk returns a tuple with the PromptTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AiUsageDto) GetPromptTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PromptTokens.Get(), o.PromptTokens.IsSet()
}

// HasPromptTokens returns a boolean if a field has been set.
func (o *AiUsageDto) HasPromptTokens() bool {
	if o != nil && o.PromptTokens.IsSet() {
		return true
	}

	return false
}

// SetPromptTokens gets a reference to the given NullableInt32 and assigns it to the PromptTokens field.
func (o *AiUsageDto) SetPromptTokens(v int32) {
	o.PromptTokens.Set(&v)
}
// SetPromptTokensNil sets the value for PromptTokens to be an explicit nil
func (o *AiUsageDto) SetPromptTokensNil() {
	o.PromptTokens.Set(nil)
}

// UnsetPromptTokens ensures that no value is present for PromptTokens, not even an explicit nil
func (o *AiUsageDto) UnsetPromptTokens() {
	o.PromptTokens.Unset()
}

// GetCompletionTokens returns the CompletionTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AiUsageDto) GetCompletionTokens() int32 {
	if o == nil || IsNil(o.CompletionTokens.Get()) {
		var ret int32
		return ret
	}
	return *o.CompletionTokens.Get()
}

// GetCompletionTokensOk returns a tuple with the CompletionTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AiUsageDto) GetCompletionTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletionTokens.Get(), o.CompletionTokens.IsSet()
}

// HasCompletionTokens returns a boolean if a field has been set.
func (o *AiUsageDto) HasCompletionTokens() bool {
	if o != nil && o.CompletionTokens.IsSet() {
		return true
	}

	return false
}

// SetCompletionTokens gets a reference to the given NullableInt32 and assigns it to the CompletionTokens field.
func (o *AiUsageDto) SetCompletionTokens(v int32) {
	o.CompletionTokens.Set(&v)
}
// SetCompletionTokensNil sets the value for CompletionTokens to be an explicit nil
func (o *AiUsageDto) SetCompletionTokensNil() {
	o.CompletionTokens.Set(nil)
}

// UnsetCompletionTokens ensures that no value is present for CompletionTokens, not even an explicit nil
func (o *AiUsageDto) UnsetCompletionTokens() {
	o.CompletionTokens.Unset()
}

// GetTotalTokens returns the TotalTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AiUsageDto) GetTotalTokens() int32 {
	if o == nil || IsNil(o.TotalTokens.Get()) {
		var ret int32
		return ret
	}
	return *o.TotalTokens.Get()
}

// GetTotalTokensOk returns a tuple with the TotalTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AiUsageDto) GetTotalTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotalTokens.Get(), o.TotalTokens.IsSet()
}

// HasTotalTokens returns a boolean if a field has been set.
func (o *AiUsageDto) HasTotalTokens() bool {
	if o != nil && o.TotalTokens.IsSet() {
		return true
	}

	return false
}

// SetTotalTokens gets a reference to the given NullableInt32 and assigns it to the TotalTokens field.
func (o *AiUsageDto) SetTotalTokens(v int32) {
	o.TotalTokens.Set(&v)
}
// SetTotalTokensNil sets the value for TotalTokens to be an explicit nil
func (o *AiUsageDto) SetTotalTokensNil() {
	o.TotalTokens.Set(nil)
}

// UnsetTotalTokens ensures that no value is present for TotalTokens, not even an explicit nil
func (o *AiUsageDto) UnsetTotalTokens() {
	o.TotalTokens.Unset()
}

func (o AiUsageDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AiUsageDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.PromptTokens.IsSet() {
		toSerialize["prompt_tokens"] = o.PromptTokens.Get()
	}
	if o.CompletionTokens.IsSet() {
		toSerialize["completion_tokens"] = o.CompletionTokens.Get()
	}
	if o.TotalTokens.IsSet() {
		toSerialize["total_tokens"] = o.TotalTokens.Get()
	}
	return toSerialize, nil
}

type NullableAiUsageDto struct {
	value *AiUsageDto
	isSet bool
}

func (v NullableAiUsageDto) Get() *AiUsageDto {
	return v.value
}

func (v *NullableAiUsageDto) Set(val *AiUsageDto) {
	v.value = val
	v.isSet = true
}

func (v NullableAiUsageDto) IsSet() bool {
	return v.isSet
}

func (v *NullableAiUsageDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAiUsageDto(val *AiUsageDto) *NullableAiUsageDto {
	return &NullableAiUsageDto{value: val, isSet: true}
}

func (v NullableAiUsageDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAiUsageDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


