/*
Felorx API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package felorx

import (
	"encoding/json"
)

// checks if the FelorxResponseUsageOutputTokensDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FelorxResponseUsageOutputTokensDetails{}

// FelorxResponseUsageOutputTokensDetails struct for FelorxResponseUsageOutputTokensDetails
type FelorxResponseUsageOutputTokensDetails struct {
	ReasoningTokens *int64 `json:"reasoning_tokens,omitempty"`
}

// NewFelorxResponseUsageOutputTokensDetails instantiates a new FelorxResponseUsageOutputTokensDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFelorxResponseUsageOutputTokensDetails() *FelorxResponseUsageOutputTokensDetails {
	this := FelorxResponseUsageOutputTokensDetails{}
	return &this
}

// NewFelorxResponseUsageOutputTokensDetailsWithDefaults instantiates a new FelorxResponseUsageOutputTokensDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFelorxResponseUsageOutputTokensDetailsWithDefaults() *FelorxResponseUsageOutputTokensDetails {
	this := FelorxResponseUsageOutputTokensDetails{}
	return &this
}

// GetReasoningTokens returns the ReasoningTokens field value if set, zero value otherwise.
func (o *FelorxResponseUsageOutputTokensDetails) GetReasoningTokens() int64 {
	if o == nil || IsNil(o.ReasoningTokens) {
		var ret int64
		return ret
	}
	return *o.ReasoningTokens
}

// GetReasoningTokensOk returns a tuple with the ReasoningTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FelorxResponseUsageOutputTokensDetails) GetReasoningTokensOk() (*int64, bool) {
	if o == nil || IsNil(o.ReasoningTokens) {
		return nil, false
	}
	return o.ReasoningTokens, true
}

// HasReasoningTokens returns a boolean if a field has been set.
func (o *FelorxResponseUsageOutputTokensDetails) HasReasoningTokens() bool {
	if o != nil && !IsNil(o.ReasoningTokens) {
		return true
	}

	return false
}

// SetReasoningTokens gets a reference to the given int64 and assigns it to the ReasoningTokens field.
func (o *FelorxResponseUsageOutputTokensDetails) SetReasoningTokens(v int64) {
	o.ReasoningTokens = &v
}

func (o FelorxResponseUsageOutputTokensDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FelorxResponseUsageOutputTokensDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ReasoningTokens) {
		toSerialize["reasoning_tokens"] = o.ReasoningTokens
	}
	return toSerialize, nil
}

type NullableFelorxResponseUsageOutputTokensDetails struct {
	value *FelorxResponseUsageOutputTokensDetails
	isSet bool
}

func (v NullableFelorxResponseUsageOutputTokensDetails) Get() *FelorxResponseUsageOutputTokensDetails {
	return v.value
}

func (v *NullableFelorxResponseUsageOutputTokensDetails) Set(val *FelorxResponseUsageOutputTokensDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableFelorxResponseUsageOutputTokensDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableFelorxResponseUsageOutputTokensDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFelorxResponseUsageOutputTokensDetails(val *FelorxResponseUsageOutputTokensDetails) *NullableFelorxResponseUsageOutputTokensDetails {
	return &NullableFelorxResponseUsageOutputTokensDetails{value: val, isSet: true}
}

func (v NullableFelorxResponseUsageOutputTokensDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFelorxResponseUsageOutputTokensDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


