/*
Felorx API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package felorx

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateDeployRecordDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDeployRecordDto{}

// UpdateDeployRecordDto 更新部署记录DTO
type UpdateDeployRecordDto struct {
	Status DeployStatus `json:"status"`
	// 部署日志
	Logs NullableString `json:"logs,omitempty"`
	// 错误信息
	ErrorMessage NullableString `json:"errorMessage,omitempty"`
	// 部署地址
	DeployUrl NullableString `json:"deployUrl,omitempty"`
}

type _UpdateDeployRecordDto UpdateDeployRecordDto

// NewUpdateDeployRecordDto instantiates a new UpdateDeployRecordDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDeployRecordDto(status DeployStatus) *UpdateDeployRecordDto {
	this := UpdateDeployRecordDto{}
	this.Status = status
	return &this
}

// NewUpdateDeployRecordDtoWithDefaults instantiates a new UpdateDeployRecordDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDeployRecordDtoWithDefaults() *UpdateDeployRecordDto {
	this := UpdateDeployRecordDto{}
	return &this
}

// GetStatus returns the Status field value
func (o *UpdateDeployRecordDto) GetStatus() DeployStatus {
	if o == nil {
		var ret DeployStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdateDeployRecordDto) GetStatusOk() (*DeployStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdateDeployRecordDto) SetStatus(v DeployStatus) {
	o.Status = v
}

// GetLogs returns the Logs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateDeployRecordDto) GetLogs() string {
	if o == nil || IsNil(o.Logs.Get()) {
		var ret string
		return ret
	}
	return *o.Logs.Get()
}

// GetLogsOk returns a tuple with the Logs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateDeployRecordDto) GetLogsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Logs.Get(), o.Logs.IsSet()
}

// HasLogs returns a boolean if a field has been set.
func (o *UpdateDeployRecordDto) HasLogs() bool {
	if o != nil && o.Logs.IsSet() {
		return true
	}

	return false
}

// SetLogs gets a reference to the given NullableString and assigns it to the Logs field.
func (o *UpdateDeployRecordDto) SetLogs(v string) {
	o.Logs.Set(&v)
}

// SetLogsNil sets the value for Logs to be an explicit nil
func (o *UpdateDeployRecordDto) SetLogsNil() {
	o.Logs.Set(nil)
}

// UnsetLogs ensures that no value is present for Logs, not even an explicit nil
func (o *UpdateDeployRecordDto) UnsetLogs() {
	o.Logs.Unset()
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateDeployRecordDto) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage.Get()) {
		var ret string
		return ret
	}
	return *o.ErrorMessage.Get()
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateDeployRecordDto) GetErrorMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorMessage.Get(), o.ErrorMessage.IsSet()
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *UpdateDeployRecordDto) HasErrorMessage() bool {
	if o != nil && o.ErrorMessage.IsSet() {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given NullableString and assigns it to the ErrorMessage field.
func (o *UpdateDeployRecordDto) SetErrorMessage(v string) {
	o.ErrorMessage.Set(&v)
}

// SetErrorMessageNil sets the value for ErrorMessage to be an explicit nil
func (o *UpdateDeployRecordDto) SetErrorMessageNil() {
	o.ErrorMessage.Set(nil)
}

// UnsetErrorMessage ensures that no value is present for ErrorMessage, not even an explicit nil
func (o *UpdateDeployRecordDto) UnsetErrorMessage() {
	o.ErrorMessage.Unset()
}

// GetDeployUrl returns the DeployUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateDeployRecordDto) GetDeployUrl() string {
	if o == nil || IsNil(o.DeployUrl.Get()) {
		var ret string
		return ret
	}
	return *o.DeployUrl.Get()
}

// GetDeployUrlOk returns a tuple with the DeployUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateDeployRecordDto) GetDeployUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeployUrl.Get(), o.DeployUrl.IsSet()
}

// HasDeployUrl returns a boolean if a field has been set.
func (o *UpdateDeployRecordDto) HasDeployUrl() bool {
	if o != nil && o.DeployUrl.IsSet() {
		return true
	}

	return false
}

// SetDeployUrl gets a reference to the given NullableString and assigns it to the DeployUrl field.
func (o *UpdateDeployRecordDto) SetDeployUrl(v string) {
	o.DeployUrl.Set(&v)
}

// SetDeployUrlNil sets the value for DeployUrl to be an explicit nil
func (o *UpdateDeployRecordDto) SetDeployUrlNil() {
	o.DeployUrl.Set(nil)
}

// UnsetDeployUrl ensures that no value is present for DeployUrl, not even an explicit nil
func (o *UpdateDeployRecordDto) UnsetDeployUrl() {
	o.DeployUrl.Unset()
}

func (o UpdateDeployRecordDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDeployRecordDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	if o.Logs.IsSet() {
		toSerialize["logs"] = o.Logs.Get()
	}
	if o.ErrorMessage.IsSet() {
		toSerialize["errorMessage"] = o.ErrorMessage.Get()
	}
	if o.DeployUrl.IsSet() {
		toSerialize["deployUrl"] = o.DeployUrl.Get()
	}
	return toSerialize, nil
}

func (o *UpdateDeployRecordDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateDeployRecordDto := _UpdateDeployRecordDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateDeployRecordDto)

	if err != nil {
		return err
	}

	*o = UpdateDeployRecordDto(varUpdateDeployRecordDto)

	return err
}

type NullableUpdateDeployRecordDto struct {
	value *UpdateDeployRecordDto
	isSet bool
}

func (v NullableUpdateDeployRecordDto) Get() *UpdateDeployRecordDto {
	return v.value
}

func (v *NullableUpdateDeployRecordDto) Set(val *UpdateDeployRecordDto) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDeployRecordDto) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDeployRecordDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDeployRecordDto(val *UpdateDeployRecordDto) *NullableUpdateDeployRecordDto {
	return &NullableUpdateDeployRecordDto{value: val, isSet: true}
}

func (v NullableUpdateDeployRecordDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDeployRecordDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
