/*
Felorx API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package felorx

import (
	"encoding/json"
)

// checks if the CreateMessageTemplateReleaseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateMessageTemplateReleaseDto{}

// CreateMessageTemplateReleaseDto struct for CreateMessageTemplateReleaseDto
type CreateMessageTemplateReleaseDto struct {
	Content NullableString `json:"content,omitempty"`
	SchemaVersion *int32 `json:"schemaVersion,omitempty"`
	Status NullableString `json:"status,omitempty"`
	TemplateId *string `json:"templateId,omitempty"`
}

// NewCreateMessageTemplateReleaseDto instantiates a new CreateMessageTemplateReleaseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateMessageTemplateReleaseDto() *CreateMessageTemplateReleaseDto {
	this := CreateMessageTemplateReleaseDto{}
	return &this
}

// NewCreateMessageTemplateReleaseDtoWithDefaults instantiates a new CreateMessageTemplateReleaseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateMessageTemplateReleaseDtoWithDefaults() *CreateMessageTemplateReleaseDto {
	this := CreateMessageTemplateReleaseDto{}
	return &this
}

// GetContent returns the Content field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateMessageTemplateReleaseDto) GetContent() string {
	if o == nil || IsNil(o.Content.Get()) {
		var ret string
		return ret
	}
	return *o.Content.Get()
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateMessageTemplateReleaseDto) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Content.Get(), o.Content.IsSet()
}

// HasContent returns a boolean if a field has been set.
func (o *CreateMessageTemplateReleaseDto) HasContent() bool {
	if o != nil && o.Content.IsSet() {
		return true
	}

	return false
}

// SetContent gets a reference to the given NullableString and assigns it to the Content field.
func (o *CreateMessageTemplateReleaseDto) SetContent(v string) {
	o.Content.Set(&v)
}
// SetContentNil sets the value for Content to be an explicit nil
func (o *CreateMessageTemplateReleaseDto) SetContentNil() {
	o.Content.Set(nil)
}

// UnsetContent ensures that no value is present for Content, not even an explicit nil
func (o *CreateMessageTemplateReleaseDto) UnsetContent() {
	o.Content.Unset()
}

// GetSchemaVersion returns the SchemaVersion field value if set, zero value otherwise.
func (o *CreateMessageTemplateReleaseDto) GetSchemaVersion() int32 {
	if o == nil || IsNil(o.SchemaVersion) {
		var ret int32
		return ret
	}
	return *o.SchemaVersion
}

// GetSchemaVersionOk returns a tuple with the SchemaVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMessageTemplateReleaseDto) GetSchemaVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.SchemaVersion) {
		return nil, false
	}
	return o.SchemaVersion, true
}

// HasSchemaVersion returns a boolean if a field has been set.
func (o *CreateMessageTemplateReleaseDto) HasSchemaVersion() bool {
	if o != nil && !IsNil(o.SchemaVersion) {
		return true
	}

	return false
}

// SetSchemaVersion gets a reference to the given int32 and assigns it to the SchemaVersion field.
func (o *CreateMessageTemplateReleaseDto) SetSchemaVersion(v int32) {
	o.SchemaVersion = &v
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateMessageTemplateReleaseDto) GetStatus() string {
	if o == nil || IsNil(o.Status.Get()) {
		var ret string
		return ret
	}
	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateMessageTemplateReleaseDto) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// HasStatus returns a boolean if a field has been set.
func (o *CreateMessageTemplateReleaseDto) HasStatus() bool {
	if o != nil && o.Status.IsSet() {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NullableString and assigns it to the Status field.
func (o *CreateMessageTemplateReleaseDto) SetStatus(v string) {
	o.Status.Set(&v)
}
// SetStatusNil sets the value for Status to be an explicit nil
func (o *CreateMessageTemplateReleaseDto) SetStatusNil() {
	o.Status.Set(nil)
}

// UnsetStatus ensures that no value is present for Status, not even an explicit nil
func (o *CreateMessageTemplateReleaseDto) UnsetStatus() {
	o.Status.Unset()
}

// GetTemplateId returns the TemplateId field value if set, zero value otherwise.
func (o *CreateMessageTemplateReleaseDto) GetTemplateId() string {
	if o == nil || IsNil(o.TemplateId) {
		var ret string
		return ret
	}
	return *o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMessageTemplateReleaseDto) GetTemplateIdOk() (*string, bool) {
	if o == nil || IsNil(o.TemplateId) {
		return nil, false
	}
	return o.TemplateId, true
}

// HasTemplateId returns a boolean if a field has been set.
func (o *CreateMessageTemplateReleaseDto) HasTemplateId() bool {
	if o != nil && !IsNil(o.TemplateId) {
		return true
	}

	return false
}

// SetTemplateId gets a reference to the given string and assigns it to the TemplateId field.
func (o *CreateMessageTemplateReleaseDto) SetTemplateId(v string) {
	o.TemplateId = &v
}

func (o CreateMessageTemplateReleaseDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateMessageTemplateReleaseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Content.IsSet() {
		toSerialize["content"] = o.Content.Get()
	}
	if !IsNil(o.SchemaVersion) {
		toSerialize["schemaVersion"] = o.SchemaVersion
	}
	if o.Status.IsSet() {
		toSerialize["status"] = o.Status.Get()
	}
	if !IsNil(o.TemplateId) {
		toSerialize["templateId"] = o.TemplateId
	}
	return toSerialize, nil
}

type NullableCreateMessageTemplateReleaseDto struct {
	value *CreateMessageTemplateReleaseDto
	isSet bool
}

func (v NullableCreateMessageTemplateReleaseDto) Get() *CreateMessageTemplateReleaseDto {
	return v.value
}

func (v *NullableCreateMessageTemplateReleaseDto) Set(val *CreateMessageTemplateReleaseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateMessageTemplateReleaseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateMessageTemplateReleaseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateMessageTemplateReleaseDto(val *CreateMessageTemplateReleaseDto) *NullableCreateMessageTemplateReleaseDto {
	return &NullableCreateMessageTemplateReleaseDto{value: val, isSet: true}
}

func (v NullableCreateMessageTemplateReleaseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateMessageTemplateReleaseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


