/*
Felorx API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package felorx

import (
	"encoding/json"
)

// checks if the CreateOrUpdateAiModelDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrUpdateAiModelDto{}

// CreateOrUpdateAiModelDto struct for CreateOrUpdateAiModelDto
type CreateOrUpdateAiModelDto struct {
	RouteName NullableString `json:"route_name,omitempty"`
	Name NullableString `json:"name,omitempty"`
	DisplayName NullableString `json:"display_name,omitempty"`
	Capabilities []AiCapability `json:"capabilities,omitempty"`
	Enabled *bool `json:"enabled,omitempty"`
	IsDefault *bool `json:"is_default,omitempty"`
	DefaultParameters map[string]string `json:"default_parameters,omitempty"`
}

// NewCreateOrUpdateAiModelDto instantiates a new CreateOrUpdateAiModelDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrUpdateAiModelDto() *CreateOrUpdateAiModelDto {
	this := CreateOrUpdateAiModelDto{}
	return &this
}

// NewCreateOrUpdateAiModelDtoWithDefaults instantiates a new CreateOrUpdateAiModelDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrUpdateAiModelDtoWithDefaults() *CreateOrUpdateAiModelDto {
	this := CreateOrUpdateAiModelDto{}
	return &this
}

// GetRouteName returns the RouteName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrUpdateAiModelDto) GetRouteName() string {
	if o == nil || IsNil(o.RouteName.Get()) {
		var ret string
		return ret
	}
	return *o.RouteName.Get()
}

// GetRouteNameOk returns a tuple with the RouteName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrUpdateAiModelDto) GetRouteNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RouteName.Get(), o.RouteName.IsSet()
}

// HasRouteName returns a boolean if a field has been set.
func (o *CreateOrUpdateAiModelDto) HasRouteName() bool {
	if o != nil && o.RouteName.IsSet() {
		return true
	}

	return false
}

// SetRouteName gets a reference to the given NullableString and assigns it to the RouteName field.
func (o *CreateOrUpdateAiModelDto) SetRouteName(v string) {
	o.RouteName.Set(&v)
}
// SetRouteNameNil sets the value for RouteName to be an explicit nil
func (o *CreateOrUpdateAiModelDto) SetRouteNameNil() {
	o.RouteName.Set(nil)
}

// UnsetRouteName ensures that no value is present for RouteName, not even an explicit nil
func (o *CreateOrUpdateAiModelDto) UnsetRouteName() {
	o.RouteName.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrUpdateAiModelDto) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrUpdateAiModelDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *CreateOrUpdateAiModelDto) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *CreateOrUpdateAiModelDto) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *CreateOrUpdateAiModelDto) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *CreateOrUpdateAiModelDto) UnsetName() {
	o.Name.Unset()
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrUpdateAiModelDto) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName.Get()) {
		var ret string
		return ret
	}
	return *o.DisplayName.Get()
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrUpdateAiModelDto) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DisplayName.Get(), o.DisplayName.IsSet()
}

// HasDisplayName returns a boolean if a field has been set.
func (o *CreateOrUpdateAiModelDto) HasDisplayName() bool {
	if o != nil && o.DisplayName.IsSet() {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given NullableString and assigns it to the DisplayName field.
func (o *CreateOrUpdateAiModelDto) SetDisplayName(v string) {
	o.DisplayName.Set(&v)
}
// SetDisplayNameNil sets the value for DisplayName to be an explicit nil
func (o *CreateOrUpdateAiModelDto) SetDisplayNameNil() {
	o.DisplayName.Set(nil)
}

// UnsetDisplayName ensures that no value is present for DisplayName, not even an explicit nil
func (o *CreateOrUpdateAiModelDto) UnsetDisplayName() {
	o.DisplayName.Unset()
}

// GetCapabilities returns the Capabilities field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrUpdateAiModelDto) GetCapabilities() []AiCapability {
	if o == nil {
		var ret []AiCapability
		return ret
	}
	return o.Capabilities
}

// GetCapabilitiesOk returns a tuple with the Capabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrUpdateAiModelDto) GetCapabilitiesOk() ([]AiCapability, bool) {
	if o == nil || IsNil(o.Capabilities) {
		return nil, false
	}
	return o.Capabilities, true
}

// HasCapabilities returns a boolean if a field has been set.
func (o *CreateOrUpdateAiModelDto) HasCapabilities() bool {
	if o != nil && !IsNil(o.Capabilities) {
		return true
	}

	return false
}

// SetCapabilities gets a reference to the given []AiCapability and assigns it to the Capabilities field.
func (o *CreateOrUpdateAiModelDto) SetCapabilities(v []AiCapability) {
	o.Capabilities = v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *CreateOrUpdateAiModelDto) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateAiModelDto) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *CreateOrUpdateAiModelDto) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *CreateOrUpdateAiModelDto) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetIsDefault returns the IsDefault field value if set, zero value otherwise.
func (o *CreateOrUpdateAiModelDto) GetIsDefault() bool {
	if o == nil || IsNil(o.IsDefault) {
		var ret bool
		return ret
	}
	return *o.IsDefault
}

// GetIsDefaultOk returns a tuple with the IsDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateAiModelDto) GetIsDefaultOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDefault) {
		return nil, false
	}
	return o.IsDefault, true
}

// HasIsDefault returns a boolean if a field has been set.
func (o *CreateOrUpdateAiModelDto) HasIsDefault() bool {
	if o != nil && !IsNil(o.IsDefault) {
		return true
	}

	return false
}

// SetIsDefault gets a reference to the given bool and assigns it to the IsDefault field.
func (o *CreateOrUpdateAiModelDto) SetIsDefault(v bool) {
	o.IsDefault = &v
}

// GetDefaultParameters returns the DefaultParameters field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrUpdateAiModelDto) GetDefaultParameters() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}
	return o.DefaultParameters
}

// GetDefaultParametersOk returns a tuple with the DefaultParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrUpdateAiModelDto) GetDefaultParametersOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.DefaultParameters) {
		return nil, false
	}
	return &o.DefaultParameters, true
}

// HasDefaultParameters returns a boolean if a field has been set.
func (o *CreateOrUpdateAiModelDto) HasDefaultParameters() bool {
	if o != nil && !IsNil(o.DefaultParameters) {
		return true
	}

	return false
}

// SetDefaultParameters gets a reference to the given map[string]string and assigns it to the DefaultParameters field.
func (o *CreateOrUpdateAiModelDto) SetDefaultParameters(v map[string]string) {
	o.DefaultParameters = v
}

func (o CreateOrUpdateAiModelDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrUpdateAiModelDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.RouteName.IsSet() {
		toSerialize["route_name"] = o.RouteName.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.DisplayName.IsSet() {
		toSerialize["display_name"] = o.DisplayName.Get()
	}
	if o.Capabilities != nil {
		toSerialize["capabilities"] = o.Capabilities
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.IsDefault) {
		toSerialize["is_default"] = o.IsDefault
	}
	if o.DefaultParameters != nil {
		toSerialize["default_parameters"] = o.DefaultParameters
	}
	return toSerialize, nil
}

type NullableCreateOrUpdateAiModelDto struct {
	value *CreateOrUpdateAiModelDto
	isSet bool
}

func (v NullableCreateOrUpdateAiModelDto) Get() *CreateOrUpdateAiModelDto {
	return v.value
}

func (v *NullableCreateOrUpdateAiModelDto) Set(val *CreateOrUpdateAiModelDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrUpdateAiModelDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrUpdateAiModelDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrUpdateAiModelDto(val *CreateOrUpdateAiModelDto) *NullableCreateOrUpdateAiModelDto {
	return &NullableCreateOrUpdateAiModelDto{value: val, isSet: true}
}

func (v NullableCreateOrUpdateAiModelDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrUpdateAiModelDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


