/*
Felorx API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package felorx

import (
	"encoding/json"
	"fmt"
)

// BillingProvider the model 'BillingProvider'
type BillingProvider string

// List of BillingProvider
const (
	BILLINGPROVIDER_UNKNOWN         BillingProvider = "Unknown"
	BILLINGPROVIDER_APPLE_APP_STORE BillingProvider = "AppleAppStore"
	BILLINGPROVIDER_PAY_PAL         BillingProvider = "PayPal"
	BILLINGPROVIDER_ALIPAY          BillingProvider = "Alipay"
)

// All allowed values of BillingProvider enum
var AllowedBillingProviderEnumValues = []BillingProvider{
	"Unknown",
	"AppleAppStore",
	"PayPal",
	"Alipay",
}

func (v *BillingProvider) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BillingProvider(value)
	for _, existing := range AllowedBillingProviderEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BillingProvider", value)
}

// NewBillingProviderFromValue returns a pointer to a valid BillingProvider
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBillingProviderFromValue(v string) (*BillingProvider, error) {
	ev := BillingProvider(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BillingProvider: valid values are %v", v, AllowedBillingProviderEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BillingProvider) IsValid() bool {
	for _, existing := range AllowedBillingProviderEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BillingProvider value
func (v BillingProvider) Ptr() *BillingProvider {
	return &v
}

type NullableBillingProvider struct {
	value *BillingProvider
	isSet bool
}

func (v NullableBillingProvider) Get() *BillingProvider {
	return v.value
}

func (v *NullableBillingProvider) Set(val *BillingProvider) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingProvider) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingProvider) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingProvider(val *BillingProvider) *NullableBillingProvider {
	return &NullableBillingProvider{value: val, isSet: true}
}

func (v NullableBillingProvider) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingProvider) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
