/*
Felorx API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package felorx

import (
	"encoding/json"
)

// checks if the OpenAiChatCompletionRequestDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenAiChatCompletionRequestDto{}

// OpenAiChatCompletionRequestDto struct for OpenAiChatCompletionRequestDto
type OpenAiChatCompletionRequestDto struct {
	Model                NullableString     `json:"model,omitempty"`
	Provider             NullableString     `json:"provider,omitempty"`
	Messages             []AiChatMessageDto `json:"messages,omitempty"`
	Temperature          NullableFloat64    `json:"temperature,omitempty"`
	TopP                 NullableFloat64    `json:"top_p,omitempty"`
	MaxTokens            NullableInt32      `json:"max_tokens,omitempty"`
	Stream               *bool              `json:"stream,omitempty"`
	Metadata             map[string]string  `json:"metadata,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OpenAiChatCompletionRequestDto OpenAiChatCompletionRequestDto

// NewOpenAiChatCompletionRequestDto instantiates a new OpenAiChatCompletionRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenAiChatCompletionRequestDto() *OpenAiChatCompletionRequestDto {
	this := OpenAiChatCompletionRequestDto{}
	return &this
}

// NewOpenAiChatCompletionRequestDtoWithDefaults instantiates a new OpenAiChatCompletionRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenAiChatCompletionRequestDtoWithDefaults() *OpenAiChatCompletionRequestDto {
	this := OpenAiChatCompletionRequestDto{}
	return &this
}

// GetModel returns the Model field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenAiChatCompletionRequestDto) GetModel() string {
	if o == nil || IsNil(o.Model.Get()) {
		var ret string
		return ret
	}
	return *o.Model.Get()
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenAiChatCompletionRequestDto) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Model.Get(), o.Model.IsSet()
}

// HasModel returns a boolean if a field has been set.
func (o *OpenAiChatCompletionRequestDto) HasModel() bool {
	if o != nil && o.Model.IsSet() {
		return true
	}

	return false
}

// SetModel gets a reference to the given NullableString and assigns it to the Model field.
func (o *OpenAiChatCompletionRequestDto) SetModel(v string) {
	o.Model.Set(&v)
}

// SetModelNil sets the value for Model to be an explicit nil
func (o *OpenAiChatCompletionRequestDto) SetModelNil() {
	o.Model.Set(nil)
}

// UnsetModel ensures that no value is present for Model, not even an explicit nil
func (o *OpenAiChatCompletionRequestDto) UnsetModel() {
	o.Model.Unset()
}

// GetProvider returns the Provider field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenAiChatCompletionRequestDto) GetProvider() string {
	if o == nil || IsNil(o.Provider.Get()) {
		var ret string
		return ret
	}
	return *o.Provider.Get()
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenAiChatCompletionRequestDto) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Provider.Get(), o.Provider.IsSet()
}

// HasProvider returns a boolean if a field has been set.
func (o *OpenAiChatCompletionRequestDto) HasProvider() bool {
	if o != nil && o.Provider.IsSet() {
		return true
	}

	return false
}

// SetProvider gets a reference to the given NullableString and assigns it to the Provider field.
func (o *OpenAiChatCompletionRequestDto) SetProvider(v string) {
	o.Provider.Set(&v)
}

// SetProviderNil sets the value for Provider to be an explicit nil
func (o *OpenAiChatCompletionRequestDto) SetProviderNil() {
	o.Provider.Set(nil)
}

// UnsetProvider ensures that no value is present for Provider, not even an explicit nil
func (o *OpenAiChatCompletionRequestDto) UnsetProvider() {
	o.Provider.Unset()
}

// GetMessages returns the Messages field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenAiChatCompletionRequestDto) GetMessages() []AiChatMessageDto {
	if o == nil {
		var ret []AiChatMessageDto
		return ret
	}
	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenAiChatCompletionRequestDto) GetMessagesOk() ([]AiChatMessageDto, bool) {
	if o == nil || IsNil(o.Messages) {
		return nil, false
	}
	return o.Messages, true
}

// HasMessages returns a boolean if a field has been set.
func (o *OpenAiChatCompletionRequestDto) HasMessages() bool {
	if o != nil && !IsNil(o.Messages) {
		return true
	}

	return false
}

// SetMessages gets a reference to the given []AiChatMessageDto and assigns it to the Messages field.
func (o *OpenAiChatCompletionRequestDto) SetMessages(v []AiChatMessageDto) {
	o.Messages = v
}

// GetTemperature returns the Temperature field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenAiChatCompletionRequestDto) GetTemperature() float64 {
	if o == nil || IsNil(o.Temperature.Get()) {
		var ret float64
		return ret
	}
	return *o.Temperature.Get()
}

// GetTemperatureOk returns a tuple with the Temperature field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenAiChatCompletionRequestDto) GetTemperatureOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Temperature.Get(), o.Temperature.IsSet()
}

// HasTemperature returns a boolean if a field has been set.
func (o *OpenAiChatCompletionRequestDto) HasTemperature() bool {
	if o != nil && o.Temperature.IsSet() {
		return true
	}

	return false
}

// SetTemperature gets a reference to the given NullableFloat64 and assigns it to the Temperature field.
func (o *OpenAiChatCompletionRequestDto) SetTemperature(v float64) {
	o.Temperature.Set(&v)
}

// SetTemperatureNil sets the value for Temperature to be an explicit nil
func (o *OpenAiChatCompletionRequestDto) SetTemperatureNil() {
	o.Temperature.Set(nil)
}

// UnsetTemperature ensures that no value is present for Temperature, not even an explicit nil
func (o *OpenAiChatCompletionRequestDto) UnsetTemperature() {
	o.Temperature.Unset()
}

// GetTopP returns the TopP field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenAiChatCompletionRequestDto) GetTopP() float64 {
	if o == nil || IsNil(o.TopP.Get()) {
		var ret float64
		return ret
	}
	return *o.TopP.Get()
}

// GetTopPOk returns a tuple with the TopP field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenAiChatCompletionRequestDto) GetTopPOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.TopP.Get(), o.TopP.IsSet()
}

// HasTopP returns a boolean if a field has been set.
func (o *OpenAiChatCompletionRequestDto) HasTopP() bool {
	if o != nil && o.TopP.IsSet() {
		return true
	}

	return false
}

// SetTopP gets a reference to the given NullableFloat64 and assigns it to the TopP field.
func (o *OpenAiChatCompletionRequestDto) SetTopP(v float64) {
	o.TopP.Set(&v)
}

// SetTopPNil sets the value for TopP to be an explicit nil
func (o *OpenAiChatCompletionRequestDto) SetTopPNil() {
	o.TopP.Set(nil)
}

// UnsetTopP ensures that no value is present for TopP, not even an explicit nil
func (o *OpenAiChatCompletionRequestDto) UnsetTopP() {
	o.TopP.Unset()
}

// GetMaxTokens returns the MaxTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenAiChatCompletionRequestDto) GetMaxTokens() int32 {
	if o == nil || IsNil(o.MaxTokens.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxTokens.Get()
}

// GetMaxTokensOk returns a tuple with the MaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenAiChatCompletionRequestDto) GetMaxTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxTokens.Get(), o.MaxTokens.IsSet()
}

// HasMaxTokens returns a boolean if a field has been set.
func (o *OpenAiChatCompletionRequestDto) HasMaxTokens() bool {
	if o != nil && o.MaxTokens.IsSet() {
		return true
	}

	return false
}

// SetMaxTokens gets a reference to the given NullableInt32 and assigns it to the MaxTokens field.
func (o *OpenAiChatCompletionRequestDto) SetMaxTokens(v int32) {
	o.MaxTokens.Set(&v)
}

// SetMaxTokensNil sets the value for MaxTokens to be an explicit nil
func (o *OpenAiChatCompletionRequestDto) SetMaxTokensNil() {
	o.MaxTokens.Set(nil)
}

// UnsetMaxTokens ensures that no value is present for MaxTokens, not even an explicit nil
func (o *OpenAiChatCompletionRequestDto) UnsetMaxTokens() {
	o.MaxTokens.Unset()
}

// GetStream returns the Stream field value if set, zero value otherwise.
func (o *OpenAiChatCompletionRequestDto) GetStream() bool {
	if o == nil || IsNil(o.Stream) {
		var ret bool
		return ret
	}
	return *o.Stream
}

// GetStreamOk returns a tuple with the Stream field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenAiChatCompletionRequestDto) GetStreamOk() (*bool, bool) {
	if o == nil || IsNil(o.Stream) {
		return nil, false
	}
	return o.Stream, true
}

// HasStream returns a boolean if a field has been set.
func (o *OpenAiChatCompletionRequestDto) HasStream() bool {
	if o != nil && !IsNil(o.Stream) {
		return true
	}

	return false
}

// SetStream gets a reference to the given bool and assigns it to the Stream field.
func (o *OpenAiChatCompletionRequestDto) SetStream(v bool) {
	o.Stream = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenAiChatCompletionRequestDto) GetMetadata() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenAiChatCompletionRequestDto) GetMetadataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return &o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *OpenAiChatCompletionRequestDto) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *OpenAiChatCompletionRequestDto) SetMetadata(v map[string]string) {
	o.Metadata = v
}

func (o OpenAiChatCompletionRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenAiChatCompletionRequestDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Model.IsSet() {
		toSerialize["model"] = o.Model.Get()
	}
	if o.Provider.IsSet() {
		toSerialize["provider"] = o.Provider.Get()
	}
	if o.Messages != nil {
		toSerialize["messages"] = o.Messages
	}
	if o.Temperature.IsSet() {
		toSerialize["temperature"] = o.Temperature.Get()
	}
	if o.TopP.IsSet() {
		toSerialize["top_p"] = o.TopP.Get()
	}
	if o.MaxTokens.IsSet() {
		toSerialize["max_tokens"] = o.MaxTokens.Get()
	}
	if !IsNil(o.Stream) {
		toSerialize["stream"] = o.Stream
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OpenAiChatCompletionRequestDto) UnmarshalJSON(data []byte) (err error) {
	varOpenAiChatCompletionRequestDto := _OpenAiChatCompletionRequestDto{}

	err = json.Unmarshal(data, &varOpenAiChatCompletionRequestDto)

	if err != nil {
		return err
	}

	*o = OpenAiChatCompletionRequestDto(varOpenAiChatCompletionRequestDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "model")
		delete(additionalProperties, "provider")
		delete(additionalProperties, "messages")
		delete(additionalProperties, "temperature")
		delete(additionalProperties, "top_p")
		delete(additionalProperties, "max_tokens")
		delete(additionalProperties, "stream")
		delete(additionalProperties, "metadata")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOpenAiChatCompletionRequestDto struct {
	value *OpenAiChatCompletionRequestDto
	isSet bool
}

func (v NullableOpenAiChatCompletionRequestDto) Get() *OpenAiChatCompletionRequestDto {
	return v.value
}

func (v *NullableOpenAiChatCompletionRequestDto) Set(val *OpenAiChatCompletionRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenAiChatCompletionRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenAiChatCompletionRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenAiChatCompletionRequestDto(val *OpenAiChatCompletionRequestDto) *NullableOpenAiChatCompletionRequestDto {
	return &NullableOpenAiChatCompletionRequestDto{value: val, isSet: true}
}

func (v NullableOpenAiChatCompletionRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenAiChatCompletionRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
