/*
Felorx API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package felorx

import (
	"encoding/json"
	"time"
)

// checks if the AiModelDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AiModelDto{}

// AiModelDto struct for AiModelDto
type AiModelDto struct {
	Id *string `json:"id,omitempty"`
	CreationTime *time.Time `json:"creationTime,omitempty"`
	CreatorId NullableString `json:"creatorId,omitempty"`
	LastModificationTime NullableTime `json:"lastModificationTime,omitempty"`
	LastModifierId NullableString `json:"lastModifierId,omitempty"`
	IsDeleted *bool `json:"isDeleted,omitempty"`
	DeleterId NullableString `json:"deleterId,omitempty"`
	DeletionTime NullableTime `json:"deletionTime,omitempty"`
	VerifiedCapabilities []AiCapability `json:"verified_capabilities,omitempty"`
	CapabilityCertificateVersion NullableString `json:"capability_certificate_version,omitempty"`
	CapabilityTestedAt NullableTime `json:"capability_tested_at,omitempty"`
	ProviderId *string `json:"provider_id,omitempty"`
	RouteName NullableString `json:"route_name,omitempty"`
	Name NullableString `json:"name,omitempty"`
	DisplayName NullableString `json:"display_name,omitempty"`
	Capabilities []AiCapability `json:"capabilities,omitempty"`
	Enabled *bool `json:"enabled,omitempty"`
	IsDefault *bool `json:"is_default,omitempty"`
	DefaultParameters map[string]string `json:"default_parameters,omitempty"`
}

// NewAiModelDto instantiates a new AiModelDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAiModelDto() *AiModelDto {
	this := AiModelDto{}
	return &this
}

// NewAiModelDtoWithDefaults instantiates a new AiModelDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAiModelDtoWithDefaults() *AiModelDto {
	this := AiModelDto{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AiModelDto) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiModelDto) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AiModelDto) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AiModelDto) SetId(v string) {
	o.Id = &v
}

// GetCreationTime returns the CreationTime field value if set, zero value otherwise.
func (o *AiModelDto) GetCreationTime() time.Time {
	if o == nil || IsNil(o.CreationTime) {
		var ret time.Time
		return ret
	}
	return *o.CreationTime
}

// GetCreationTimeOk returns a tuple with the CreationTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiModelDto) GetCreationTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreationTime) {
		return nil, false
	}
	return o.CreationTime, true
}

// HasCreationTime returns a boolean if a field has been set.
func (o *AiModelDto) HasCreationTime() bool {
	if o != nil && !IsNil(o.CreationTime) {
		return true
	}

	return false
}

// SetCreationTime gets a reference to the given time.Time and assigns it to the CreationTime field.
func (o *AiModelDto) SetCreationTime(v time.Time) {
	o.CreationTime = &v
}

// GetCreatorId returns the CreatorId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AiModelDto) GetCreatorId() string {
	if o == nil || IsNil(o.CreatorId.Get()) {
		var ret string
		return ret
	}
	return *o.CreatorId.Get()
}

// GetCreatorIdOk returns a tuple with the CreatorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AiModelDto) GetCreatorIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatorId.Get(), o.CreatorId.IsSet()
}

// HasCreatorId returns a boolean if a field has been set.
func (o *AiModelDto) HasCreatorId() bool {
	if o != nil && o.CreatorId.IsSet() {
		return true
	}

	return false
}

// SetCreatorId gets a reference to the given NullableString and assigns it to the CreatorId field.
func (o *AiModelDto) SetCreatorId(v string) {
	o.CreatorId.Set(&v)
}
// SetCreatorIdNil sets the value for CreatorId to be an explicit nil
func (o *AiModelDto) SetCreatorIdNil() {
	o.CreatorId.Set(nil)
}

// UnsetCreatorId ensures that no value is present for CreatorId, not even an explicit nil
func (o *AiModelDto) UnsetCreatorId() {
	o.CreatorId.Unset()
}

// GetLastModificationTime returns the LastModificationTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AiModelDto) GetLastModificationTime() time.Time {
	if o == nil || IsNil(o.LastModificationTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastModificationTime.Get()
}

// GetLastModificationTimeOk returns a tuple with the LastModificationTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AiModelDto) GetLastModificationTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastModificationTime.Get(), o.LastModificationTime.IsSet()
}

// HasLastModificationTime returns a boolean if a field has been set.
func (o *AiModelDto) HasLastModificationTime() bool {
	if o != nil && o.LastModificationTime.IsSet() {
		return true
	}

	return false
}

// SetLastModificationTime gets a reference to the given NullableTime and assigns it to the LastModificationTime field.
func (o *AiModelDto) SetLastModificationTime(v time.Time) {
	o.LastModificationTime.Set(&v)
}
// SetLastModificationTimeNil sets the value for LastModificationTime to be an explicit nil
func (o *AiModelDto) SetLastModificationTimeNil() {
	o.LastModificationTime.Set(nil)
}

// UnsetLastModificationTime ensures that no value is present for LastModificationTime, not even an explicit nil
func (o *AiModelDto) UnsetLastModificationTime() {
	o.LastModificationTime.Unset()
}

// GetLastModifierId returns the LastModifierId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AiModelDto) GetLastModifierId() string {
	if o == nil || IsNil(o.LastModifierId.Get()) {
		var ret string
		return ret
	}
	return *o.LastModifierId.Get()
}

// GetLastModifierIdOk returns a tuple with the LastModifierId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AiModelDto) GetLastModifierIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastModifierId.Get(), o.LastModifierId.IsSet()
}

// HasLastModifierId returns a boolean if a field has been set.
func (o *AiModelDto) HasLastModifierId() bool {
	if o != nil && o.LastModifierId.IsSet() {
		return true
	}

	return false
}

// SetLastModifierId gets a reference to the given NullableString and assigns it to the LastModifierId field.
func (o *AiModelDto) SetLastModifierId(v string) {
	o.LastModifierId.Set(&v)
}
// SetLastModifierIdNil sets the value for LastModifierId to be an explicit nil
func (o *AiModelDto) SetLastModifierIdNil() {
	o.LastModifierId.Set(nil)
}

// UnsetLastModifierId ensures that no value is present for LastModifierId, not even an explicit nil
func (o *AiModelDto) UnsetLastModifierId() {
	o.LastModifierId.Unset()
}

// GetIsDeleted returns the IsDeleted field value if set, zero value otherwise.
func (o *AiModelDto) GetIsDeleted() bool {
	if o == nil || IsNil(o.IsDeleted) {
		var ret bool
		return ret
	}
	return *o.IsDeleted
}

// GetIsDeletedOk returns a tuple with the IsDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiModelDto) GetIsDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDeleted) {
		return nil, false
	}
	return o.IsDeleted, true
}

// HasIsDeleted returns a boolean if a field has been set.
func (o *AiModelDto) HasIsDeleted() bool {
	if o != nil && !IsNil(o.IsDeleted) {
		return true
	}

	return false
}

// SetIsDeleted gets a reference to the given bool and assigns it to the IsDeleted field.
func (o *AiModelDto) SetIsDeleted(v bool) {
	o.IsDeleted = &v
}

// GetDeleterId returns the DeleterId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AiModelDto) GetDeleterId() string {
	if o == nil || IsNil(o.DeleterId.Get()) {
		var ret string
		return ret
	}
	return *o.DeleterId.Get()
}

// GetDeleterIdOk returns a tuple with the DeleterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AiModelDto) GetDeleterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeleterId.Get(), o.DeleterId.IsSet()
}

// HasDeleterId returns a boolean if a field has been set.
func (o *AiModelDto) HasDeleterId() bool {
	if o != nil && o.DeleterId.IsSet() {
		return true
	}

	return false
}

// SetDeleterId gets a reference to the given NullableString and assigns it to the DeleterId field.
func (o *AiModelDto) SetDeleterId(v string) {
	o.DeleterId.Set(&v)
}
// SetDeleterIdNil sets the value for DeleterId to be an explicit nil
func (o *AiModelDto) SetDeleterIdNil() {
	o.DeleterId.Set(nil)
}

// UnsetDeleterId ensures that no value is present for DeleterId, not even an explicit nil
func (o *AiModelDto) UnsetDeleterId() {
	o.DeleterId.Unset()
}

// GetDeletionTime returns the DeletionTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AiModelDto) GetDeletionTime() time.Time {
	if o == nil || IsNil(o.DeletionTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.DeletionTime.Get()
}

// GetDeletionTimeOk returns a tuple with the DeletionTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AiModelDto) GetDeletionTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeletionTime.Get(), o.DeletionTime.IsSet()
}

// HasDeletionTime returns a boolean if a field has been set.
func (o *AiModelDto) HasDeletionTime() bool {
	if o != nil && o.DeletionTime.IsSet() {
		return true
	}

	return false
}

// SetDeletionTime gets a reference to the given NullableTime and assigns it to the DeletionTime field.
func (o *AiModelDto) SetDeletionTime(v time.Time) {
	o.DeletionTime.Set(&v)
}
// SetDeletionTimeNil sets the value for DeletionTime to be an explicit nil
func (o *AiModelDto) SetDeletionTimeNil() {
	o.DeletionTime.Set(nil)
}

// UnsetDeletionTime ensures that no value is present for DeletionTime, not even an explicit nil
func (o *AiModelDto) UnsetDeletionTime() {
	o.DeletionTime.Unset()
}

// GetVerifiedCapabilities returns the VerifiedCapabilities field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AiModelDto) GetVerifiedCapabilities() []AiCapability {
	if o == nil {
		var ret []AiCapability
		return ret
	}
	return o.VerifiedCapabilities
}

// GetVerifiedCapabilitiesOk returns a tuple with the VerifiedCapabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AiModelDto) GetVerifiedCapabilitiesOk() ([]AiCapability, bool) {
	if o == nil || IsNil(o.VerifiedCapabilities) {
		return nil, false
	}
	return o.VerifiedCapabilities, true
}

// HasVerifiedCapabilities returns a boolean if a field has been set.
func (o *AiModelDto) HasVerifiedCapabilities() bool {
	if o != nil && !IsNil(o.VerifiedCapabilities) {
		return true
	}

	return false
}

// SetVerifiedCapabilities gets a reference to the given []AiCapability and assigns it to the VerifiedCapabilities field.
func (o *AiModelDto) SetVerifiedCapabilities(v []AiCapability) {
	o.VerifiedCapabilities = v
}

// GetCapabilityCertificateVersion returns the CapabilityCertificateVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AiModelDto) GetCapabilityCertificateVersion() string {
	if o == nil || IsNil(o.CapabilityCertificateVersion.Get()) {
		var ret string
		return ret
	}
	return *o.CapabilityCertificateVersion.Get()
}

// GetCapabilityCertificateVersionOk returns a tuple with the CapabilityCertificateVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AiModelDto) GetCapabilityCertificateVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CapabilityCertificateVersion.Get(), o.CapabilityCertificateVersion.IsSet()
}

// HasCapabilityCertificateVersion returns a boolean if a field has been set.
func (o *AiModelDto) HasCapabilityCertificateVersion() bool {
	if o != nil && o.CapabilityCertificateVersion.IsSet() {
		return true
	}

	return false
}

// SetCapabilityCertificateVersion gets a reference to the given NullableString and assigns it to the CapabilityCertificateVersion field.
func (o *AiModelDto) SetCapabilityCertificateVersion(v string) {
	o.CapabilityCertificateVersion.Set(&v)
}
// SetCapabilityCertificateVersionNil sets the value for CapabilityCertificateVersion to be an explicit nil
func (o *AiModelDto) SetCapabilityCertificateVersionNil() {
	o.CapabilityCertificateVersion.Set(nil)
}

// UnsetCapabilityCertificateVersion ensures that no value is present for CapabilityCertificateVersion, not even an explicit nil
func (o *AiModelDto) UnsetCapabilityCertificateVersion() {
	o.CapabilityCertificateVersion.Unset()
}

// GetCapabilityTestedAt returns the CapabilityTestedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AiModelDto) GetCapabilityTestedAt() time.Time {
	if o == nil || IsNil(o.CapabilityTestedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CapabilityTestedAt.Get()
}

// GetCapabilityTestedAtOk returns a tuple with the CapabilityTestedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AiModelDto) GetCapabilityTestedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CapabilityTestedAt.Get(), o.CapabilityTestedAt.IsSet()
}

// HasCapabilityTestedAt returns a boolean if a field has been set.
func (o *AiModelDto) HasCapabilityTestedAt() bool {
	if o != nil && o.CapabilityTestedAt.IsSet() {
		return true
	}

	return false
}

// SetCapabilityTestedAt gets a reference to the given NullableTime and assigns it to the CapabilityTestedAt field.
func (o *AiModelDto) SetCapabilityTestedAt(v time.Time) {
	o.CapabilityTestedAt.Set(&v)
}
// SetCapabilityTestedAtNil sets the value for CapabilityTestedAt to be an explicit nil
func (o *AiModelDto) SetCapabilityTestedAtNil() {
	o.CapabilityTestedAt.Set(nil)
}

// UnsetCapabilityTestedAt ensures that no value is present for CapabilityTestedAt, not even an explicit nil
func (o *AiModelDto) UnsetCapabilityTestedAt() {
	o.CapabilityTestedAt.Unset()
}

// GetProviderId returns the ProviderId field value if set, zero value otherwise.
func (o *AiModelDto) GetProviderId() string {
	if o == nil || IsNil(o.ProviderId) {
		var ret string
		return ret
	}
	return *o.ProviderId
}

// GetProviderIdOk returns a tuple with the ProviderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiModelDto) GetProviderIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProviderId) {
		return nil, false
	}
	return o.ProviderId, true
}

// HasProviderId returns a boolean if a field has been set.
func (o *AiModelDto) HasProviderId() bool {
	if o != nil && !IsNil(o.ProviderId) {
		return true
	}

	return false
}

// SetProviderId gets a reference to the given string and assigns it to the ProviderId field.
func (o *AiModelDto) SetProviderId(v string) {
	o.ProviderId = &v
}

// GetRouteName returns the RouteName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AiModelDto) GetRouteName() string {
	if o == nil || IsNil(o.RouteName.Get()) {
		var ret string
		return ret
	}
	return *o.RouteName.Get()
}

// GetRouteNameOk returns a tuple with the RouteName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AiModelDto) GetRouteNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RouteName.Get(), o.RouteName.IsSet()
}

// HasRouteName returns a boolean if a field has been set.
func (o *AiModelDto) HasRouteName() bool {
	if o != nil && o.RouteName.IsSet() {
		return true
	}

	return false
}

// SetRouteName gets a reference to the given NullableString and assigns it to the RouteName field.
func (o *AiModelDto) SetRouteName(v string) {
	o.RouteName.Set(&v)
}
// SetRouteNameNil sets the value for RouteName to be an explicit nil
func (o *AiModelDto) SetRouteNameNil() {
	o.RouteName.Set(nil)
}

// UnsetRouteName ensures that no value is present for RouteName, not even an explicit nil
func (o *AiModelDto) UnsetRouteName() {
	o.RouteName.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AiModelDto) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AiModelDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *AiModelDto) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *AiModelDto) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *AiModelDto) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *AiModelDto) UnsetName() {
	o.Name.Unset()
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AiModelDto) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName.Get()) {
		var ret string
		return ret
	}
	return *o.DisplayName.Get()
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AiModelDto) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DisplayName.Get(), o.DisplayName.IsSet()
}

// HasDisplayName returns a boolean if a field has been set.
func (o *AiModelDto) HasDisplayName() bool {
	if o != nil && o.DisplayName.IsSet() {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given NullableString and assigns it to the DisplayName field.
func (o *AiModelDto) SetDisplayName(v string) {
	o.DisplayName.Set(&v)
}
// SetDisplayNameNil sets the value for DisplayName to be an explicit nil
func (o *AiModelDto) SetDisplayNameNil() {
	o.DisplayName.Set(nil)
}

// UnsetDisplayName ensures that no value is present for DisplayName, not even an explicit nil
func (o *AiModelDto) UnsetDisplayName() {
	o.DisplayName.Unset()
}

// GetCapabilities returns the Capabilities field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AiModelDto) GetCapabilities() []AiCapability {
	if o == nil {
		var ret []AiCapability
		return ret
	}
	return o.Capabilities
}

// GetCapabilitiesOk returns a tuple with the Capabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AiModelDto) GetCapabilitiesOk() ([]AiCapability, bool) {
	if o == nil || IsNil(o.Capabilities) {
		return nil, false
	}
	return o.Capabilities, true
}

// HasCapabilities returns a boolean if a field has been set.
func (o *AiModelDto) HasCapabilities() bool {
	if o != nil && !IsNil(o.Capabilities) {
		return true
	}

	return false
}

// SetCapabilities gets a reference to the given []AiCapability and assigns it to the Capabilities field.
func (o *AiModelDto) SetCapabilities(v []AiCapability) {
	o.Capabilities = v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *AiModelDto) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiModelDto) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *AiModelDto) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *AiModelDto) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetIsDefault returns the IsDefault field value if set, zero value otherwise.
func (o *AiModelDto) GetIsDefault() bool {
	if o == nil || IsNil(o.IsDefault) {
		var ret bool
		return ret
	}
	return *o.IsDefault
}

// GetIsDefaultOk returns a tuple with the IsDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiModelDto) GetIsDefaultOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDefault) {
		return nil, false
	}
	return o.IsDefault, true
}

// HasIsDefault returns a boolean if a field has been set.
func (o *AiModelDto) HasIsDefault() bool {
	if o != nil && !IsNil(o.IsDefault) {
		return true
	}

	return false
}

// SetIsDefault gets a reference to the given bool and assigns it to the IsDefault field.
func (o *AiModelDto) SetIsDefault(v bool) {
	o.IsDefault = &v
}

// GetDefaultParameters returns the DefaultParameters field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AiModelDto) GetDefaultParameters() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}
	return o.DefaultParameters
}

// GetDefaultParametersOk returns a tuple with the DefaultParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AiModelDto) GetDefaultParametersOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.DefaultParameters) {
		return nil, false
	}
	return &o.DefaultParameters, true
}

// HasDefaultParameters returns a boolean if a field has been set.
func (o *AiModelDto) HasDefaultParameters() bool {
	if o != nil && !IsNil(o.DefaultParameters) {
		return true
	}

	return false
}

// SetDefaultParameters gets a reference to the given map[string]string and assigns it to the DefaultParameters field.
func (o *AiModelDto) SetDefaultParameters(v map[string]string) {
	o.DefaultParameters = v
}

func (o AiModelDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AiModelDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CreationTime) {
		toSerialize["creationTime"] = o.CreationTime
	}
	if o.CreatorId.IsSet() {
		toSerialize["creatorId"] = o.CreatorId.Get()
	}
	if o.LastModificationTime.IsSet() {
		toSerialize["lastModificationTime"] = o.LastModificationTime.Get()
	}
	if o.LastModifierId.IsSet() {
		toSerialize["lastModifierId"] = o.LastModifierId.Get()
	}
	if !IsNil(o.IsDeleted) {
		toSerialize["isDeleted"] = o.IsDeleted
	}
	if o.DeleterId.IsSet() {
		toSerialize["deleterId"] = o.DeleterId.Get()
	}
	if o.DeletionTime.IsSet() {
		toSerialize["deletionTime"] = o.DeletionTime.Get()
	}
	if o.VerifiedCapabilities != nil {
		toSerialize["verified_capabilities"] = o.VerifiedCapabilities
	}
	if o.CapabilityCertificateVersion.IsSet() {
		toSerialize["capability_certificate_version"] = o.CapabilityCertificateVersion.Get()
	}
	if o.CapabilityTestedAt.IsSet() {
		toSerialize["capability_tested_at"] = o.CapabilityTestedAt.Get()
	}
	if !IsNil(o.ProviderId) {
		toSerialize["provider_id"] = o.ProviderId
	}
	if o.RouteName.IsSet() {
		toSerialize["route_name"] = o.RouteName.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.DisplayName.IsSet() {
		toSerialize["display_name"] = o.DisplayName.Get()
	}
	if o.Capabilities != nil {
		toSerialize["capabilities"] = o.Capabilities
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.IsDefault) {
		toSerialize["is_default"] = o.IsDefault
	}
	if o.DefaultParameters != nil {
		toSerialize["default_parameters"] = o.DefaultParameters
	}
	return toSerialize, nil
}

type NullableAiModelDto struct {
	value *AiModelDto
	isSet bool
}

func (v NullableAiModelDto) Get() *AiModelDto {
	return v.value
}

func (v *NullableAiModelDto) Set(val *AiModelDto) {
	v.value = val
	v.isSet = true
}

func (v NullableAiModelDto) IsSet() bool {
	return v.isSet
}

func (v *NullableAiModelDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAiModelDto(val *AiModelDto) *NullableAiModelDto {
	return &NullableAiModelDto{value: val, isSet: true}
}

func (v NullableAiModelDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAiModelDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


