/*
Felorx API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package felorx

import (
	"encoding/json"
)

// checks if the CreateOrUpdateAppPricingDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrUpdateAppPricingDto{}

// CreateOrUpdateAppPricingDto struct for CreateOrUpdateAppPricingDto
type CreateOrUpdateAppPricingDto struct {
	Naming *AppPriceNaming `json:"naming,omitempty"`
	// 简单描述  适用于个人网站和任何想用基本的聊天方式与游客交流的人。  适用于希望改善客户关系的早期创业公司。  为需要全功能解决方案与客户沟通的公司而设。
	Description NullableString `json:"description,omitempty"`
	// APPID
	AppId *string `json:"appId,omitempty"`
	// 排序
	SortIndex *int32 `json:"sortIndex,omitempty"`
	// 收费点
	Items []AppPricingItemValueDto `json:"items,omitempty"`
}

// NewCreateOrUpdateAppPricingDto instantiates a new CreateOrUpdateAppPricingDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrUpdateAppPricingDto() *CreateOrUpdateAppPricingDto {
	this := CreateOrUpdateAppPricingDto{}
	return &this
}

// NewCreateOrUpdateAppPricingDtoWithDefaults instantiates a new CreateOrUpdateAppPricingDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrUpdateAppPricingDtoWithDefaults() *CreateOrUpdateAppPricingDto {
	this := CreateOrUpdateAppPricingDto{}
	return &this
}

// GetNaming returns the Naming field value if set, zero value otherwise.
func (o *CreateOrUpdateAppPricingDto) GetNaming() AppPriceNaming {
	if o == nil || IsNil(o.Naming) {
		var ret AppPriceNaming
		return ret
	}
	return *o.Naming
}

// GetNamingOk returns a tuple with the Naming field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateAppPricingDto) GetNamingOk() (*AppPriceNaming, bool) {
	if o == nil || IsNil(o.Naming) {
		return nil, false
	}
	return o.Naming, true
}

// HasNaming returns a boolean if a field has been set.
func (o *CreateOrUpdateAppPricingDto) HasNaming() bool {
	if o != nil && !IsNil(o.Naming) {
		return true
	}

	return false
}

// SetNaming gets a reference to the given AppPriceNaming and assigns it to the Naming field.
func (o *CreateOrUpdateAppPricingDto) SetNaming(v AppPriceNaming) {
	o.Naming = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrUpdateAppPricingDto) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrUpdateAppPricingDto) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateOrUpdateAppPricingDto) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *CreateOrUpdateAppPricingDto) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *CreateOrUpdateAppPricingDto) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *CreateOrUpdateAppPricingDto) UnsetDescription() {
	o.Description.Unset()
}

// GetAppId returns the AppId field value if set, zero value otherwise.
func (o *CreateOrUpdateAppPricingDto) GetAppId() string {
	if o == nil || IsNil(o.AppId) {
		var ret string
		return ret
	}
	return *o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateAppPricingDto) GetAppIdOk() (*string, bool) {
	if o == nil || IsNil(o.AppId) {
		return nil, false
	}
	return o.AppId, true
}

// HasAppId returns a boolean if a field has been set.
func (o *CreateOrUpdateAppPricingDto) HasAppId() bool {
	if o != nil && !IsNil(o.AppId) {
		return true
	}

	return false
}

// SetAppId gets a reference to the given string and assigns it to the AppId field.
func (o *CreateOrUpdateAppPricingDto) SetAppId(v string) {
	o.AppId = &v
}

// GetSortIndex returns the SortIndex field value if set, zero value otherwise.
func (o *CreateOrUpdateAppPricingDto) GetSortIndex() int32 {
	if o == nil || IsNil(o.SortIndex) {
		var ret int32
		return ret
	}
	return *o.SortIndex
}

// GetSortIndexOk returns a tuple with the SortIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateAppPricingDto) GetSortIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.SortIndex) {
		return nil, false
	}
	return o.SortIndex, true
}

// HasSortIndex returns a boolean if a field has been set.
func (o *CreateOrUpdateAppPricingDto) HasSortIndex() bool {
	if o != nil && !IsNil(o.SortIndex) {
		return true
	}

	return false
}

// SetSortIndex gets a reference to the given int32 and assigns it to the SortIndex field.
func (o *CreateOrUpdateAppPricingDto) SetSortIndex(v int32) {
	o.SortIndex = &v
}

// GetItems returns the Items field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrUpdateAppPricingDto) GetItems() []AppPricingItemValueDto {
	if o == nil {
		var ret []AppPricingItemValueDto
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrUpdateAppPricingDto) GetItemsOk() ([]AppPricingItemValueDto, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *CreateOrUpdateAppPricingDto) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []AppPricingItemValueDto and assigns it to the Items field.
func (o *CreateOrUpdateAppPricingDto) SetItems(v []AppPricingItemValueDto) {
	o.Items = v
}

func (o CreateOrUpdateAppPricingDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrUpdateAppPricingDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Naming) {
		toSerialize["naming"] = o.Naming
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.AppId) {
		toSerialize["appId"] = o.AppId
	}
	if !IsNil(o.SortIndex) {
		toSerialize["sortIndex"] = o.SortIndex
	}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableCreateOrUpdateAppPricingDto struct {
	value *CreateOrUpdateAppPricingDto
	isSet bool
}

func (v NullableCreateOrUpdateAppPricingDto) Get() *CreateOrUpdateAppPricingDto {
	return v.value
}

func (v *NullableCreateOrUpdateAppPricingDto) Set(val *CreateOrUpdateAppPricingDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrUpdateAppPricingDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrUpdateAppPricingDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrUpdateAppPricingDto(val *CreateOrUpdateAppPricingDto) *NullableCreateOrUpdateAppPricingDto {
	return &NullableCreateOrUpdateAppPricingDto{value: val, isSet: true}
}

func (v NullableCreateOrUpdateAppPricingDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrUpdateAppPricingDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
