/*
Felorx API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package felorx

import (
	"encoding/json"
)

// checks if the FelorxResponseUsageInputTokensDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FelorxResponseUsageInputTokensDetails{}

// FelorxResponseUsageInputTokensDetails struct for FelorxResponseUsageInputTokensDetails
type FelorxResponseUsageInputTokensDetails struct {
	CachedTokens *int64 `json:"cached_tokens,omitempty"`
}

// NewFelorxResponseUsageInputTokensDetails instantiates a new FelorxResponseUsageInputTokensDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFelorxResponseUsageInputTokensDetails() *FelorxResponseUsageInputTokensDetails {
	this := FelorxResponseUsageInputTokensDetails{}
	return &this
}

// NewFelorxResponseUsageInputTokensDetailsWithDefaults instantiates a new FelorxResponseUsageInputTokensDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFelorxResponseUsageInputTokensDetailsWithDefaults() *FelorxResponseUsageInputTokensDetails {
	this := FelorxResponseUsageInputTokensDetails{}
	return &this
}

// GetCachedTokens returns the CachedTokens field value if set, zero value otherwise.
func (o *FelorxResponseUsageInputTokensDetails) GetCachedTokens() int64 {
	if o == nil || IsNil(o.CachedTokens) {
		var ret int64
		return ret
	}
	return *o.CachedTokens
}

// GetCachedTokensOk returns a tuple with the CachedTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FelorxResponseUsageInputTokensDetails) GetCachedTokensOk() (*int64, bool) {
	if o == nil || IsNil(o.CachedTokens) {
		return nil, false
	}
	return o.CachedTokens, true
}

// HasCachedTokens returns a boolean if a field has been set.
func (o *FelorxResponseUsageInputTokensDetails) HasCachedTokens() bool {
	if o != nil && !IsNil(o.CachedTokens) {
		return true
	}

	return false
}

// SetCachedTokens gets a reference to the given int64 and assigns it to the CachedTokens field.
func (o *FelorxResponseUsageInputTokensDetails) SetCachedTokens(v int64) {
	o.CachedTokens = &v
}

func (o FelorxResponseUsageInputTokensDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FelorxResponseUsageInputTokensDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CachedTokens) {
		toSerialize["cached_tokens"] = o.CachedTokens
	}
	return toSerialize, nil
}

type NullableFelorxResponseUsageInputTokensDetails struct {
	value *FelorxResponseUsageInputTokensDetails
	isSet bool
}

func (v NullableFelorxResponseUsageInputTokensDetails) Get() *FelorxResponseUsageInputTokensDetails {
	return v.value
}

func (v *NullableFelorxResponseUsageInputTokensDetails) Set(val *FelorxResponseUsageInputTokensDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableFelorxResponseUsageInputTokensDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableFelorxResponseUsageInputTokensDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFelorxResponseUsageInputTokensDetails(val *FelorxResponseUsageInputTokensDetails) *NullableFelorxResponseUsageInputTokensDetails {
	return &NullableFelorxResponseUsageInputTokensDetails{value: val, isSet: true}
}

func (v NullableFelorxResponseUsageInputTokensDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFelorxResponseUsageInputTokensDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


