/*
Felorx API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package felorx

import (
	"encoding/json"
)

// checks if the FelorxResponsesCountRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FelorxResponsesCountRequest{}

// FelorxResponsesCountRequest struct for FelorxResponsesCountRequest
type FelorxResponsesCountRequest struct {
	Model *string `json:"model,omitempty"`
	Input *FelorxResponseInput `json:"input,omitempty"`
	Instructions *string `json:"instructions,omitempty"`
	PreviousResponseId *string `json:"previous_response_id,omitempty"`
	Tools []FelorxResponsesCountRequestToolsInner `json:"tools,omitempty"`
	ToolChoice *FelorxResponseToolChoice `json:"tool_choice,omitempty"`
	ParallelToolCalls *bool `json:"parallel_tool_calls,omitempty"`
	Reasoning map[string]interface{} `json:"reasoning,omitempty"`
	Text map[string]interface{} `json:"text,omitempty"`
	Truncation *string `json:"truncation,omitempty"`
	Personality *string `json:"personality,omitempty"`
}

// NewFelorxResponsesCountRequest instantiates a new FelorxResponsesCountRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFelorxResponsesCountRequest() *FelorxResponsesCountRequest {
	this := FelorxResponsesCountRequest{}
	return &this
}

// NewFelorxResponsesCountRequestWithDefaults instantiates a new FelorxResponsesCountRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFelorxResponsesCountRequestWithDefaults() *FelorxResponsesCountRequest {
	this := FelorxResponsesCountRequest{}
	return &this
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *FelorxResponsesCountRequest) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FelorxResponsesCountRequest) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *FelorxResponsesCountRequest) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *FelorxResponsesCountRequest) SetModel(v string) {
	o.Model = &v
}

// GetInput returns the Input field value if set, zero value otherwise.
func (o *FelorxResponsesCountRequest) GetInput() FelorxResponseInput {
	if o == nil || IsNil(o.Input) {
		var ret FelorxResponseInput
		return ret
	}
	return *o.Input
}

// GetInputOk returns a tuple with the Input field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FelorxResponsesCountRequest) GetInputOk() (*FelorxResponseInput, bool) {
	if o == nil || IsNil(o.Input) {
		return nil, false
	}
	return o.Input, true
}

// HasInput returns a boolean if a field has been set.
func (o *FelorxResponsesCountRequest) HasInput() bool {
	if o != nil && !IsNil(o.Input) {
		return true
	}

	return false
}

// SetInput gets a reference to the given FelorxResponseInput and assigns it to the Input field.
func (o *FelorxResponsesCountRequest) SetInput(v FelorxResponseInput) {
	o.Input = &v
}

// GetInstructions returns the Instructions field value if set, zero value otherwise.
func (o *FelorxResponsesCountRequest) GetInstructions() string {
	if o == nil || IsNil(o.Instructions) {
		var ret string
		return ret
	}
	return *o.Instructions
}

// GetInstructionsOk returns a tuple with the Instructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FelorxResponsesCountRequest) GetInstructionsOk() (*string, bool) {
	if o == nil || IsNil(o.Instructions) {
		return nil, false
	}
	return o.Instructions, true
}

// HasInstructions returns a boolean if a field has been set.
func (o *FelorxResponsesCountRequest) HasInstructions() bool {
	if o != nil && !IsNil(o.Instructions) {
		return true
	}

	return false
}

// SetInstructions gets a reference to the given string and assigns it to the Instructions field.
func (o *FelorxResponsesCountRequest) SetInstructions(v string) {
	o.Instructions = &v
}

// GetPreviousResponseId returns the PreviousResponseId field value if set, zero value otherwise.
func (o *FelorxResponsesCountRequest) GetPreviousResponseId() string {
	if o == nil || IsNil(o.PreviousResponseId) {
		var ret string
		return ret
	}
	return *o.PreviousResponseId
}

// GetPreviousResponseIdOk returns a tuple with the PreviousResponseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FelorxResponsesCountRequest) GetPreviousResponseIdOk() (*string, bool) {
	if o == nil || IsNil(o.PreviousResponseId) {
		return nil, false
	}
	return o.PreviousResponseId, true
}

// HasPreviousResponseId returns a boolean if a field has been set.
func (o *FelorxResponsesCountRequest) HasPreviousResponseId() bool {
	if o != nil && !IsNil(o.PreviousResponseId) {
		return true
	}

	return false
}

// SetPreviousResponseId gets a reference to the given string and assigns it to the PreviousResponseId field.
func (o *FelorxResponsesCountRequest) SetPreviousResponseId(v string) {
	o.PreviousResponseId = &v
}

// GetTools returns the Tools field value if set, zero value otherwise.
func (o *FelorxResponsesCountRequest) GetTools() []FelorxResponsesCountRequestToolsInner {
	if o == nil || IsNil(o.Tools) {
		var ret []FelorxResponsesCountRequestToolsInner
		return ret
	}
	return o.Tools
}

// GetToolsOk returns a tuple with the Tools field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FelorxResponsesCountRequest) GetToolsOk() ([]FelorxResponsesCountRequestToolsInner, bool) {
	if o == nil || IsNil(o.Tools) {
		return nil, false
	}
	return o.Tools, true
}

// HasTools returns a boolean if a field has been set.
func (o *FelorxResponsesCountRequest) HasTools() bool {
	if o != nil && !IsNil(o.Tools) {
		return true
	}

	return false
}

// SetTools gets a reference to the given []FelorxResponsesCountRequestToolsInner and assigns it to the Tools field.
func (o *FelorxResponsesCountRequest) SetTools(v []FelorxResponsesCountRequestToolsInner) {
	o.Tools = v
}

// GetToolChoice returns the ToolChoice field value if set, zero value otherwise.
func (o *FelorxResponsesCountRequest) GetToolChoice() FelorxResponseToolChoice {
	if o == nil || IsNil(o.ToolChoice) {
		var ret FelorxResponseToolChoice
		return ret
	}
	return *o.ToolChoice
}

// GetToolChoiceOk returns a tuple with the ToolChoice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FelorxResponsesCountRequest) GetToolChoiceOk() (*FelorxResponseToolChoice, bool) {
	if o == nil || IsNil(o.ToolChoice) {
		return nil, false
	}
	return o.ToolChoice, true
}

// HasToolChoice returns a boolean if a field has been set.
func (o *FelorxResponsesCountRequest) HasToolChoice() bool {
	if o != nil && !IsNil(o.ToolChoice) {
		return true
	}

	return false
}

// SetToolChoice gets a reference to the given FelorxResponseToolChoice and assigns it to the ToolChoice field.
func (o *FelorxResponsesCountRequest) SetToolChoice(v FelorxResponseToolChoice) {
	o.ToolChoice = &v
}

// GetParallelToolCalls returns the ParallelToolCalls field value if set, zero value otherwise.
func (o *FelorxResponsesCountRequest) GetParallelToolCalls() bool {
	if o == nil || IsNil(o.ParallelToolCalls) {
		var ret bool
		return ret
	}
	return *o.ParallelToolCalls
}

// GetParallelToolCallsOk returns a tuple with the ParallelToolCalls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FelorxResponsesCountRequest) GetParallelToolCallsOk() (*bool, bool) {
	if o == nil || IsNil(o.ParallelToolCalls) {
		return nil, false
	}
	return o.ParallelToolCalls, true
}

// HasParallelToolCalls returns a boolean if a field has been set.
func (o *FelorxResponsesCountRequest) HasParallelToolCalls() bool {
	if o != nil && !IsNil(o.ParallelToolCalls) {
		return true
	}

	return false
}

// SetParallelToolCalls gets a reference to the given bool and assigns it to the ParallelToolCalls field.
func (o *FelorxResponsesCountRequest) SetParallelToolCalls(v bool) {
	o.ParallelToolCalls = &v
}

// GetReasoning returns the Reasoning field value if set, zero value otherwise.
func (o *FelorxResponsesCountRequest) GetReasoning() map[string]interface{} {
	if o == nil || IsNil(o.Reasoning) {
		var ret map[string]interface{}
		return ret
	}
	return o.Reasoning
}

// GetReasoningOk returns a tuple with the Reasoning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FelorxResponsesCountRequest) GetReasoningOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Reasoning) {
		return map[string]interface{}{}, false
	}
	return o.Reasoning, true
}

// HasReasoning returns a boolean if a field has been set.
func (o *FelorxResponsesCountRequest) HasReasoning() bool {
	if o != nil && !IsNil(o.Reasoning) {
		return true
	}

	return false
}

// SetReasoning gets a reference to the given map[string]interface{} and assigns it to the Reasoning field.
func (o *FelorxResponsesCountRequest) SetReasoning(v map[string]interface{}) {
	o.Reasoning = v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *FelorxResponsesCountRequest) GetText() map[string]interface{} {
	if o == nil || IsNil(o.Text) {
		var ret map[string]interface{}
		return ret
	}
	return o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FelorxResponsesCountRequest) GetTextOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Text) {
		return map[string]interface{}{}, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *FelorxResponsesCountRequest) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given map[string]interface{} and assigns it to the Text field.
func (o *FelorxResponsesCountRequest) SetText(v map[string]interface{}) {
	o.Text = v
}

// GetTruncation returns the Truncation field value if set, zero value otherwise.
func (o *FelorxResponsesCountRequest) GetTruncation() string {
	if o == nil || IsNil(o.Truncation) {
		var ret string
		return ret
	}
	return *o.Truncation
}

// GetTruncationOk returns a tuple with the Truncation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FelorxResponsesCountRequest) GetTruncationOk() (*string, bool) {
	if o == nil || IsNil(o.Truncation) {
		return nil, false
	}
	return o.Truncation, true
}

// HasTruncation returns a boolean if a field has been set.
func (o *FelorxResponsesCountRequest) HasTruncation() bool {
	if o != nil && !IsNil(o.Truncation) {
		return true
	}

	return false
}

// SetTruncation gets a reference to the given string and assigns it to the Truncation field.
func (o *FelorxResponsesCountRequest) SetTruncation(v string) {
	o.Truncation = &v
}

// GetPersonality returns the Personality field value if set, zero value otherwise.
func (o *FelorxResponsesCountRequest) GetPersonality() string {
	if o == nil || IsNil(o.Personality) {
		var ret string
		return ret
	}
	return *o.Personality
}

// GetPersonalityOk returns a tuple with the Personality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FelorxResponsesCountRequest) GetPersonalityOk() (*string, bool) {
	if o == nil || IsNil(o.Personality) {
		return nil, false
	}
	return o.Personality, true
}

// HasPersonality returns a boolean if a field has been set.
func (o *FelorxResponsesCountRequest) HasPersonality() bool {
	if o != nil && !IsNil(o.Personality) {
		return true
	}

	return false
}

// SetPersonality gets a reference to the given string and assigns it to the Personality field.
func (o *FelorxResponsesCountRequest) SetPersonality(v string) {
	o.Personality = &v
}

func (o FelorxResponsesCountRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FelorxResponsesCountRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.Input) {
		toSerialize["input"] = o.Input
	}
	if !IsNil(o.Instructions) {
		toSerialize["instructions"] = o.Instructions
	}
	if !IsNil(o.PreviousResponseId) {
		toSerialize["previous_response_id"] = o.PreviousResponseId
	}
	if !IsNil(o.Tools) {
		toSerialize["tools"] = o.Tools
	}
	if !IsNil(o.ToolChoice) {
		toSerialize["tool_choice"] = o.ToolChoice
	}
	if !IsNil(o.ParallelToolCalls) {
		toSerialize["parallel_tool_calls"] = o.ParallelToolCalls
	}
	if !IsNil(o.Reasoning) {
		toSerialize["reasoning"] = o.Reasoning
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.Truncation) {
		toSerialize["truncation"] = o.Truncation
	}
	if !IsNil(o.Personality) {
		toSerialize["personality"] = o.Personality
	}
	return toSerialize, nil
}

type NullableFelorxResponsesCountRequest struct {
	value *FelorxResponsesCountRequest
	isSet bool
}

func (v NullableFelorxResponsesCountRequest) Get() *FelorxResponsesCountRequest {
	return v.value
}

func (v *NullableFelorxResponsesCountRequest) Set(val *FelorxResponsesCountRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFelorxResponsesCountRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFelorxResponsesCountRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFelorxResponsesCountRequest(val *FelorxResponsesCountRequest) *NullableFelorxResponsesCountRequest {
	return &NullableFelorxResponsesCountRequest{value: val, isSet: true}
}

func (v NullableFelorxResponsesCountRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFelorxResponsesCountRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


