/*
Felorx API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package felorx

import (
	"encoding/json"
)

// checks if the AppStorefrontFeatureBlockDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppStorefrontFeatureBlockDto{}

// AppStorefrontFeatureBlockDto struct for AppStorefrontFeatureBlockDto
type AppStorefrontFeatureBlockDto struct {
	FeatureId   *string        `json:"featureId,omitempty"`
	Name        NullableString `json:"name,omitempty"`
	DisplayName NullableString `json:"displayName,omitempty"`
	Description NullableString `json:"description,omitempty"`
	PhoneUrl    NullableString `json:"phoneUrl,omitempty"`
	TabletUrl   NullableString `json:"tabletUrl,omitempty"`
}

// NewAppStorefrontFeatureBlockDto instantiates a new AppStorefrontFeatureBlockDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppStorefrontFeatureBlockDto() *AppStorefrontFeatureBlockDto {
	this := AppStorefrontFeatureBlockDto{}
	return &this
}

// NewAppStorefrontFeatureBlockDtoWithDefaults instantiates a new AppStorefrontFeatureBlockDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppStorefrontFeatureBlockDtoWithDefaults() *AppStorefrontFeatureBlockDto {
	this := AppStorefrontFeatureBlockDto{}
	return &this
}

// GetFeatureId returns the FeatureId field value if set, zero value otherwise.
func (o *AppStorefrontFeatureBlockDto) GetFeatureId() string {
	if o == nil || IsNil(o.FeatureId) {
		var ret string
		return ret
	}
	return *o.FeatureId
}

// GetFeatureIdOk returns a tuple with the FeatureId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppStorefrontFeatureBlockDto) GetFeatureIdOk() (*string, bool) {
	if o == nil || IsNil(o.FeatureId) {
		return nil, false
	}
	return o.FeatureId, true
}

// HasFeatureId returns a boolean if a field has been set.
func (o *AppStorefrontFeatureBlockDto) HasFeatureId() bool {
	if o != nil && !IsNil(o.FeatureId) {
		return true
	}

	return false
}

// SetFeatureId gets a reference to the given string and assigns it to the FeatureId field.
func (o *AppStorefrontFeatureBlockDto) SetFeatureId(v string) {
	o.FeatureId = &v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppStorefrontFeatureBlockDto) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppStorefrontFeatureBlockDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *AppStorefrontFeatureBlockDto) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *AppStorefrontFeatureBlockDto) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *AppStorefrontFeatureBlockDto) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *AppStorefrontFeatureBlockDto) UnsetName() {
	o.Name.Unset()
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppStorefrontFeatureBlockDto) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName.Get()) {
		var ret string
		return ret
	}
	return *o.DisplayName.Get()
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppStorefrontFeatureBlockDto) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DisplayName.Get(), o.DisplayName.IsSet()
}

// HasDisplayName returns a boolean if a field has been set.
func (o *AppStorefrontFeatureBlockDto) HasDisplayName() bool {
	if o != nil && o.DisplayName.IsSet() {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given NullableString and assigns it to the DisplayName field.
func (o *AppStorefrontFeatureBlockDto) SetDisplayName(v string) {
	o.DisplayName.Set(&v)
}

// SetDisplayNameNil sets the value for DisplayName to be an explicit nil
func (o *AppStorefrontFeatureBlockDto) SetDisplayNameNil() {
	o.DisplayName.Set(nil)
}

// UnsetDisplayName ensures that no value is present for DisplayName, not even an explicit nil
func (o *AppStorefrontFeatureBlockDto) UnsetDisplayName() {
	o.DisplayName.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppStorefrontFeatureBlockDto) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppStorefrontFeatureBlockDto) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *AppStorefrontFeatureBlockDto) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *AppStorefrontFeatureBlockDto) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *AppStorefrontFeatureBlockDto) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *AppStorefrontFeatureBlockDto) UnsetDescription() {
	o.Description.Unset()
}

// GetPhoneUrl returns the PhoneUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppStorefrontFeatureBlockDto) GetPhoneUrl() string {
	if o == nil || IsNil(o.PhoneUrl.Get()) {
		var ret string
		return ret
	}
	return *o.PhoneUrl.Get()
}

// GetPhoneUrlOk returns a tuple with the PhoneUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppStorefrontFeatureBlockDto) GetPhoneUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PhoneUrl.Get(), o.PhoneUrl.IsSet()
}

// HasPhoneUrl returns a boolean if a field has been set.
func (o *AppStorefrontFeatureBlockDto) HasPhoneUrl() bool {
	if o != nil && o.PhoneUrl.IsSet() {
		return true
	}

	return false
}

// SetPhoneUrl gets a reference to the given NullableString and assigns it to the PhoneUrl field.
func (o *AppStorefrontFeatureBlockDto) SetPhoneUrl(v string) {
	o.PhoneUrl.Set(&v)
}

// SetPhoneUrlNil sets the value for PhoneUrl to be an explicit nil
func (o *AppStorefrontFeatureBlockDto) SetPhoneUrlNil() {
	o.PhoneUrl.Set(nil)
}

// UnsetPhoneUrl ensures that no value is present for PhoneUrl, not even an explicit nil
func (o *AppStorefrontFeatureBlockDto) UnsetPhoneUrl() {
	o.PhoneUrl.Unset()
}

// GetTabletUrl returns the TabletUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppStorefrontFeatureBlockDto) GetTabletUrl() string {
	if o == nil || IsNil(o.TabletUrl.Get()) {
		var ret string
		return ret
	}
	return *o.TabletUrl.Get()
}

// GetTabletUrlOk returns a tuple with the TabletUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppStorefrontFeatureBlockDto) GetTabletUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TabletUrl.Get(), o.TabletUrl.IsSet()
}

// HasTabletUrl returns a boolean if a field has been set.
func (o *AppStorefrontFeatureBlockDto) HasTabletUrl() bool {
	if o != nil && o.TabletUrl.IsSet() {
		return true
	}

	return false
}

// SetTabletUrl gets a reference to the given NullableString and assigns it to the TabletUrl field.
func (o *AppStorefrontFeatureBlockDto) SetTabletUrl(v string) {
	o.TabletUrl.Set(&v)
}

// SetTabletUrlNil sets the value for TabletUrl to be an explicit nil
func (o *AppStorefrontFeatureBlockDto) SetTabletUrlNil() {
	o.TabletUrl.Set(nil)
}

// UnsetTabletUrl ensures that no value is present for TabletUrl, not even an explicit nil
func (o *AppStorefrontFeatureBlockDto) UnsetTabletUrl() {
	o.TabletUrl.Unset()
}

func (o AppStorefrontFeatureBlockDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppStorefrontFeatureBlockDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FeatureId) {
		toSerialize["featureId"] = o.FeatureId
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.DisplayName.IsSet() {
		toSerialize["displayName"] = o.DisplayName.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.PhoneUrl.IsSet() {
		toSerialize["phoneUrl"] = o.PhoneUrl.Get()
	}
	if o.TabletUrl.IsSet() {
		toSerialize["tabletUrl"] = o.TabletUrl.Get()
	}
	return toSerialize, nil
}

type NullableAppStorefrontFeatureBlockDto struct {
	value *AppStorefrontFeatureBlockDto
	isSet bool
}

func (v NullableAppStorefrontFeatureBlockDto) Get() *AppStorefrontFeatureBlockDto {
	return v.value
}

func (v *NullableAppStorefrontFeatureBlockDto) Set(val *AppStorefrontFeatureBlockDto) {
	v.value = val
	v.isSet = true
}

func (v NullableAppStorefrontFeatureBlockDto) IsSet() bool {
	return v.isSet
}

func (v *NullableAppStorefrontFeatureBlockDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppStorefrontFeatureBlockDto(val *AppStorefrontFeatureBlockDto) *NullableAppStorefrontFeatureBlockDto {
	return &NullableAppStorefrontFeatureBlockDto{value: val, isSet: true}
}

func (v NullableAppStorefrontFeatureBlockDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppStorefrontFeatureBlockDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
