/*
Felorx API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package felorx

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateAppFeedbackDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAppFeedbackDto{}

// CreateAppFeedbackDto 创建应用反馈DTO
type CreateAppFeedbackDto struct {
	// 应用ID
	AppId string `json:"appId"`
	// 反馈内容
	Content string          `json:"content"`
	Type    AppFeedbackType `json:"type"`
	// 联系方式（可选）
	Contact NullableString `json:"contact,omitempty"`
	// 设备信息（可选）
	DeviceInfo NullableString `json:"deviceInfo,omitempty"`
	// 应用版本（可选）
	AppVersion NullableString `json:"appVersion,omitempty"`
	// 截图/图片附件（对象存储 key，最多 5 个）
	AttachmentKeys []string `json:"attachmentKeys,omitempty"`
}

type _CreateAppFeedbackDto CreateAppFeedbackDto

// NewCreateAppFeedbackDto instantiates a new CreateAppFeedbackDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAppFeedbackDto(appId string, content string, type_ AppFeedbackType) *CreateAppFeedbackDto {
	this := CreateAppFeedbackDto{}
	this.AppId = appId
	this.Content = content
	this.Type = type_
	return &this
}

// NewCreateAppFeedbackDtoWithDefaults instantiates a new CreateAppFeedbackDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAppFeedbackDtoWithDefaults() *CreateAppFeedbackDto {
	this := CreateAppFeedbackDto{}
	return &this
}

// GetAppId returns the AppId field value
func (o *CreateAppFeedbackDto) GetAppId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value
// and a boolean to check if the value has been set.
func (o *CreateAppFeedbackDto) GetAppIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppId, true
}

// SetAppId sets field value
func (o *CreateAppFeedbackDto) SetAppId(v string) {
	o.AppId = v
}

// GetContent returns the Content field value
func (o *CreateAppFeedbackDto) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *CreateAppFeedbackDto) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *CreateAppFeedbackDto) SetContent(v string) {
	o.Content = v
}

// GetType returns the Type field value
func (o *CreateAppFeedbackDto) GetType() AppFeedbackType {
	if o == nil {
		var ret AppFeedbackType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateAppFeedbackDto) GetTypeOk() (*AppFeedbackType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateAppFeedbackDto) SetType(v AppFeedbackType) {
	o.Type = v
}

// GetContact returns the Contact field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAppFeedbackDto) GetContact() string {
	if o == nil || IsNil(o.Contact.Get()) {
		var ret string
		return ret
	}
	return *o.Contact.Get()
}

// GetContactOk returns a tuple with the Contact field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAppFeedbackDto) GetContactOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Contact.Get(), o.Contact.IsSet()
}

// HasContact returns a boolean if a field has been set.
func (o *CreateAppFeedbackDto) HasContact() bool {
	if o != nil && o.Contact.IsSet() {
		return true
	}

	return false
}

// SetContact gets a reference to the given NullableString and assigns it to the Contact field.
func (o *CreateAppFeedbackDto) SetContact(v string) {
	o.Contact.Set(&v)
}

// SetContactNil sets the value for Contact to be an explicit nil
func (o *CreateAppFeedbackDto) SetContactNil() {
	o.Contact.Set(nil)
}

// UnsetContact ensures that no value is present for Contact, not even an explicit nil
func (o *CreateAppFeedbackDto) UnsetContact() {
	o.Contact.Unset()
}

// GetDeviceInfo returns the DeviceInfo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAppFeedbackDto) GetDeviceInfo() string {
	if o == nil || IsNil(o.DeviceInfo.Get()) {
		var ret string
		return ret
	}
	return *o.DeviceInfo.Get()
}

// GetDeviceInfoOk returns a tuple with the DeviceInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAppFeedbackDto) GetDeviceInfoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeviceInfo.Get(), o.DeviceInfo.IsSet()
}

// HasDeviceInfo returns a boolean if a field has been set.
func (o *CreateAppFeedbackDto) HasDeviceInfo() bool {
	if o != nil && o.DeviceInfo.IsSet() {
		return true
	}

	return false
}

// SetDeviceInfo gets a reference to the given NullableString and assigns it to the DeviceInfo field.
func (o *CreateAppFeedbackDto) SetDeviceInfo(v string) {
	o.DeviceInfo.Set(&v)
}

// SetDeviceInfoNil sets the value for DeviceInfo to be an explicit nil
func (o *CreateAppFeedbackDto) SetDeviceInfoNil() {
	o.DeviceInfo.Set(nil)
}

// UnsetDeviceInfo ensures that no value is present for DeviceInfo, not even an explicit nil
func (o *CreateAppFeedbackDto) UnsetDeviceInfo() {
	o.DeviceInfo.Unset()
}

// GetAppVersion returns the AppVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAppFeedbackDto) GetAppVersion() string {
	if o == nil || IsNil(o.AppVersion.Get()) {
		var ret string
		return ret
	}
	return *o.AppVersion.Get()
}

// GetAppVersionOk returns a tuple with the AppVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAppFeedbackDto) GetAppVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AppVersion.Get(), o.AppVersion.IsSet()
}

// HasAppVersion returns a boolean if a field has been set.
func (o *CreateAppFeedbackDto) HasAppVersion() bool {
	if o != nil && o.AppVersion.IsSet() {
		return true
	}

	return false
}

// SetAppVersion gets a reference to the given NullableString and assigns it to the AppVersion field.
func (o *CreateAppFeedbackDto) SetAppVersion(v string) {
	o.AppVersion.Set(&v)
}

// SetAppVersionNil sets the value for AppVersion to be an explicit nil
func (o *CreateAppFeedbackDto) SetAppVersionNil() {
	o.AppVersion.Set(nil)
}

// UnsetAppVersion ensures that no value is present for AppVersion, not even an explicit nil
func (o *CreateAppFeedbackDto) UnsetAppVersion() {
	o.AppVersion.Unset()
}

// GetAttachmentKeys returns the AttachmentKeys field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAppFeedbackDto) GetAttachmentKeys() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.AttachmentKeys
}

// GetAttachmentKeysOk returns a tuple with the AttachmentKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAppFeedbackDto) GetAttachmentKeysOk() ([]string, bool) {
	if o == nil || IsNil(o.AttachmentKeys) {
		return nil, false
	}
	return o.AttachmentKeys, true
}

// HasAttachmentKeys returns a boolean if a field has been set.
func (o *CreateAppFeedbackDto) HasAttachmentKeys() bool {
	if o != nil && !IsNil(o.AttachmentKeys) {
		return true
	}

	return false
}

// SetAttachmentKeys gets a reference to the given []string and assigns it to the AttachmentKeys field.
func (o *CreateAppFeedbackDto) SetAttachmentKeys(v []string) {
	o.AttachmentKeys = v
}

func (o CreateAppFeedbackDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAppFeedbackDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["appId"] = o.AppId
	toSerialize["content"] = o.Content
	toSerialize["type"] = o.Type
	if o.Contact.IsSet() {
		toSerialize["contact"] = o.Contact.Get()
	}
	if o.DeviceInfo.IsSet() {
		toSerialize["deviceInfo"] = o.DeviceInfo.Get()
	}
	if o.AppVersion.IsSet() {
		toSerialize["appVersion"] = o.AppVersion.Get()
	}
	if o.AttachmentKeys != nil {
		toSerialize["attachmentKeys"] = o.AttachmentKeys
	}
	return toSerialize, nil
}

func (o *CreateAppFeedbackDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"appId",
		"content",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAppFeedbackDto := _CreateAppFeedbackDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateAppFeedbackDto)

	if err != nil {
		return err
	}

	*o = CreateAppFeedbackDto(varCreateAppFeedbackDto)

	return err
}

type NullableCreateAppFeedbackDto struct {
	value *CreateAppFeedbackDto
	isSet bool
}

func (v NullableCreateAppFeedbackDto) Get() *CreateAppFeedbackDto {
	return v.value
}

func (v *NullableCreateAppFeedbackDto) Set(val *CreateAppFeedbackDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAppFeedbackDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAppFeedbackDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAppFeedbackDto(val *CreateAppFeedbackDto) *NullableCreateAppFeedbackDto {
	return &NullableCreateAppFeedbackDto{value: val, isSet: true}
}

func (v NullableCreateAppFeedbackDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAppFeedbackDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
