/*
Felorx API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package felorx

import (
	"encoding/json"
)

// checks if the CreatePayPalOrderDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePayPalOrderDto{}

// CreatePayPalOrderDto 创建 PayPal 订单请求
type CreatePayPalOrderDto struct {
	// 应用 ID
	AppId *string `json:"appId,omitempty"`
	// 定价方案 ID
	PricingId *string `json:"pricingId,omitempty"`
	// 计划类型：month=月度, year=年度, three_year=三年, lifetime=终身
	PlanType NullableString `json:"planType,omitempty"`
	// 支付完成后返回地址，桌面端可传深链。
	ReturnUrl NullableString `json:"returnUrl,omitempty"`
	// 支付取消后返回地址，桌面端可传深链。
	CancelUrl NullableString `json:"cancelUrl,omitempty"`
}

// NewCreatePayPalOrderDto instantiates a new CreatePayPalOrderDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePayPalOrderDto() *CreatePayPalOrderDto {
	this := CreatePayPalOrderDto{}
	return &this
}

// NewCreatePayPalOrderDtoWithDefaults instantiates a new CreatePayPalOrderDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePayPalOrderDtoWithDefaults() *CreatePayPalOrderDto {
	this := CreatePayPalOrderDto{}
	return &this
}

// GetAppId returns the AppId field value if set, zero value otherwise.
func (o *CreatePayPalOrderDto) GetAppId() string {
	if o == nil || IsNil(o.AppId) {
		var ret string
		return ret
	}
	return *o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePayPalOrderDto) GetAppIdOk() (*string, bool) {
	if o == nil || IsNil(o.AppId) {
		return nil, false
	}
	return o.AppId, true
}

// HasAppId returns a boolean if a field has been set.
func (o *CreatePayPalOrderDto) HasAppId() bool {
	if o != nil && !IsNil(o.AppId) {
		return true
	}

	return false
}

// SetAppId gets a reference to the given string and assigns it to the AppId field.
func (o *CreatePayPalOrderDto) SetAppId(v string) {
	o.AppId = &v
}

// GetPricingId returns the PricingId field value if set, zero value otherwise.
func (o *CreatePayPalOrderDto) GetPricingId() string {
	if o == nil || IsNil(o.PricingId) {
		var ret string
		return ret
	}
	return *o.PricingId
}

// GetPricingIdOk returns a tuple with the PricingId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePayPalOrderDto) GetPricingIdOk() (*string, bool) {
	if o == nil || IsNil(o.PricingId) {
		return nil, false
	}
	return o.PricingId, true
}

// HasPricingId returns a boolean if a field has been set.
func (o *CreatePayPalOrderDto) HasPricingId() bool {
	if o != nil && !IsNil(o.PricingId) {
		return true
	}

	return false
}

// SetPricingId gets a reference to the given string and assigns it to the PricingId field.
func (o *CreatePayPalOrderDto) SetPricingId(v string) {
	o.PricingId = &v
}

// GetPlanType returns the PlanType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreatePayPalOrderDto) GetPlanType() string {
	if o == nil || IsNil(o.PlanType.Get()) {
		var ret string
		return ret
	}
	return *o.PlanType.Get()
}

// GetPlanTypeOk returns a tuple with the PlanType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatePayPalOrderDto) GetPlanTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PlanType.Get(), o.PlanType.IsSet()
}

// HasPlanType returns a boolean if a field has been set.
func (o *CreatePayPalOrderDto) HasPlanType() bool {
	if o != nil && o.PlanType.IsSet() {
		return true
	}

	return false
}

// SetPlanType gets a reference to the given NullableString and assigns it to the PlanType field.
func (o *CreatePayPalOrderDto) SetPlanType(v string) {
	o.PlanType.Set(&v)
}
// SetPlanTypeNil sets the value for PlanType to be an explicit nil
func (o *CreatePayPalOrderDto) SetPlanTypeNil() {
	o.PlanType.Set(nil)
}

// UnsetPlanType ensures that no value is present for PlanType, not even an explicit nil
func (o *CreatePayPalOrderDto) UnsetPlanType() {
	o.PlanType.Unset()
}

// GetReturnUrl returns the ReturnUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreatePayPalOrderDto) GetReturnUrl() string {
	if o == nil || IsNil(o.ReturnUrl.Get()) {
		var ret string
		return ret
	}
	return *o.ReturnUrl.Get()
}

// GetReturnUrlOk returns a tuple with the ReturnUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatePayPalOrderDto) GetReturnUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReturnUrl.Get(), o.ReturnUrl.IsSet()
}

// HasReturnUrl returns a boolean if a field has been set.
func (o *CreatePayPalOrderDto) HasReturnUrl() bool {
	if o != nil && o.ReturnUrl.IsSet() {
		return true
	}

	return false
}

// SetReturnUrl gets a reference to the given NullableString and assigns it to the ReturnUrl field.
func (o *CreatePayPalOrderDto) SetReturnUrl(v string) {
	o.ReturnUrl.Set(&v)
}
// SetReturnUrlNil sets the value for ReturnUrl to be an explicit nil
func (o *CreatePayPalOrderDto) SetReturnUrlNil() {
	o.ReturnUrl.Set(nil)
}

// UnsetReturnUrl ensures that no value is present for ReturnUrl, not even an explicit nil
func (o *CreatePayPalOrderDto) UnsetReturnUrl() {
	o.ReturnUrl.Unset()
}

// GetCancelUrl returns the CancelUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreatePayPalOrderDto) GetCancelUrl() string {
	if o == nil || IsNil(o.CancelUrl.Get()) {
		var ret string
		return ret
	}
	return *o.CancelUrl.Get()
}

// GetCancelUrlOk returns a tuple with the CancelUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatePayPalOrderDto) GetCancelUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CancelUrl.Get(), o.CancelUrl.IsSet()
}

// HasCancelUrl returns a boolean if a field has been set.
func (o *CreatePayPalOrderDto) HasCancelUrl() bool {
	if o != nil && o.CancelUrl.IsSet() {
		return true
	}

	return false
}

// SetCancelUrl gets a reference to the given NullableString and assigns it to the CancelUrl field.
func (o *CreatePayPalOrderDto) SetCancelUrl(v string) {
	o.CancelUrl.Set(&v)
}
// SetCancelUrlNil sets the value for CancelUrl to be an explicit nil
func (o *CreatePayPalOrderDto) SetCancelUrlNil() {
	o.CancelUrl.Set(nil)
}

// UnsetCancelUrl ensures that no value is present for CancelUrl, not even an explicit nil
func (o *CreatePayPalOrderDto) UnsetCancelUrl() {
	o.CancelUrl.Unset()
}

func (o CreatePayPalOrderDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePayPalOrderDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AppId) {
		toSerialize["appId"] = o.AppId
	}
	if !IsNil(o.PricingId) {
		toSerialize["pricingId"] = o.PricingId
	}
	if o.PlanType.IsSet() {
		toSerialize["planType"] = o.PlanType.Get()
	}
	if o.ReturnUrl.IsSet() {
		toSerialize["returnUrl"] = o.ReturnUrl.Get()
	}
	if o.CancelUrl.IsSet() {
		toSerialize["cancelUrl"] = o.CancelUrl.Get()
	}
	return toSerialize, nil
}

type NullableCreatePayPalOrderDto struct {
	value *CreatePayPalOrderDto
	isSet bool
}

func (v NullableCreatePayPalOrderDto) Get() *CreatePayPalOrderDto {
	return v.value
}

func (v *NullableCreatePayPalOrderDto) Set(val *CreatePayPalOrderDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePayPalOrderDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePayPalOrderDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePayPalOrderDto(val *CreatePayPalOrderDto) *NullableCreatePayPalOrderDto {
	return &NullableCreatePayPalOrderDto{value: val, isSet: true}
}

func (v NullableCreatePayPalOrderDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePayPalOrderDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


